// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: controlplane.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const cordonHost = `-- name: CordonHost :execrows
UPDATE hosts SET status = 'cordoned'
WHERE id = $1 AND status IN ('ready', 'notready')
`

// Operator takes a host out of scheduling while its replicas keep running.
// Only agent-owned states may be cordoned: a draining host is already leaving
// and re-labelling it would erase that intent. rows = 0 means "not applicable".
func (q *Queries) CordonHost(ctx context.Context, hostID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, cordonHost, hostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteStaleApiserverInstances = `-- name: DeleteStaleApiserverInstances :exec
DELETE FROM apiserver_instances WHERE heartbeat_at < $1
`

// Instances silent past the liveness window are gone (crashed without
// deregistering); reap them so they can't anchor the grace computation.
func (q *Queries) DeleteStaleApiserverInstances(ctx context.Context, heartbeatBefore time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteStaleApiserverInstances, heartbeatBefore)
	return err
}

const deregisterApiserverInstance = `-- name: DeregisterApiserverInstance :exec
DELETE FROM apiserver_instances WHERE id = $1
`

func (q *Queries) DeregisterApiserverInstance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deregisterApiserverInstance, id)
	return err
}

const drainHost = `-- name: DrainHost :execrows
UPDATE hosts SET status = 'draining'
WHERE id = $1 AND status <> 'draining'
`

// Operator evacuates a host: the reconciler drains its replicas elsewhere.
func (q *Queries) DrainHost(ctx context.Context, hostID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, drainHost, hostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listDeploymentReplicaIDs = `-- name: ListDeploymentReplicaIDs :many
SELECT id FROM replicas
WHERE deployment_id = $1 AND phase NOT IN ('reaped', 'failed')
`

// Fan-out targets for deployment-wide agent chaos. Terminal phases are excluded:
// a reaped or failed replica has no agent left to lie about it.
func (q *Queries) ListDeploymentReplicaIDs(ctx context.Context, deploymentID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentReplicaIDs, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentRows = `-- name: ListEnvironmentRows :many
SELECT id, project_name, name FROM environments
WHERE ($1::text = '' OR project_name = $1)
  AND ($2::text = '' OR name = $2)
ORDER BY project_name, name
`

type ListEnvironmentRowsParams struct {
	Project     string `json:"project"`
	Environment string `json:"environment"`
}

type ListEnvironmentRowsRow struct {
	ID          uuid.UUID `json:"id"`
	ProjectName string    `json:"project_name"`
	Name        string    `json:"name"`
}

func (q *Queries) ListEnvironmentRows(ctx context.Context, arg ListEnvironmentRowsParams) ([]ListEnvironmentRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEnvironmentRows, arg.Project, arg.Environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEnvironmentRowsRow
	for rows.Next() {
		var i ListEnvironmentRowsRow
		if err := rows.Scan(&i.ID, &i.ProjectName, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectNames = `-- name: ListProjectNames :many

SELECT name FROM projects
WHERE ($1::text = '' OR name = $1)
ORDER BY name
`

// Topology / meta reads backing the operator UI. Every filter is a no-op when
// passed empty, so one query serves both the "everything" view and a narrowed
// one (same convention as ProjectStatus).
func (q *Queries) ListProjectNames(ctx context.Context, project string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listProjectNames, project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectServices = `-- name: ListProjectServices :many
SELECT s.id, s.name, s.stateful
FROM services s
WHERE s.project_name = $1
  AND ($2::text = '' OR EXISTS (
        SELECT 1
        FROM environment_services es
        JOIN environments e ON e.id = es.environment_id
        WHERE es.service_id = s.id
          AND e.project_name = s.project_name
          AND e.name = $2))
ORDER BY s.name
`

type ListProjectServicesParams struct {
	Project     string `json:"project"`
	Environment string `json:"environment"`
}

type ListProjectServicesRow struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Stateful bool      `json:"stateful"`
}

// Project-wide service listing for the bind form: it must offer services NOT
// yet in the environment, so the environment filter is opt-in.
func (q *Queries) ListProjectServices(ctx context.Context, arg ListProjectServicesParams) ([]ListProjectServicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProjectServices, arg.Project, arg.Environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectServicesRow
	for rows.Next() {
		var i ListProjectServicesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Stateful); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegionNames = `-- name: ListRegionNames :many
SELECT name FROM regions
ORDER BY name
`

func (q *Queries) ListRegionNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRegionNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplicas = `-- name: ListReplicas :many

SELECT id, deployment_id, region, host_id, volume_id, cpu_millicores, mem_bytes, alloc_reason, desired_status, phase, healthy, restart_count, last_exit_reason, revision, created_at, updated_at, drained_at, health_checks_passed_at FROM replicas
WHERE phase <> 'reaped'
ORDER BY created_at
`

// Control-plane API reads and operator writes (internal/api/controlplane.go),
// plus the apiserver liveness the sensor's startup grace keys on.
// Fleet-wide replica listing for the read API; reaped rows are history.
func (q *Queries) ListReplicas(ctx context.Context) ([]Replica, error) {
	rows, err := q.db.QueryContext(ctx, listReplicas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Replica
	for rows.Next() {
		var i Replica
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Region,
			&i.HostID,
			&i.VolumeID,
			&i.CpuMillicores,
			&i.MemBytes,
			&i.AllocReason,
			&i.DesiredStatus,
			&i.Phase,
			&i.Healthy,
			&i.RestartCount,
			&i.LastExitReason,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DrainedAt,
			&i.HealthChecksPassedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestLiveApiserverStart = `-- name: OldestLiveApiserverStart :one
SELECT started_at FROM apiserver_instances
WHERE heartbeat_at >= $1
ORDER BY started_at
LIMIT 1
`

// The oldest start among instances heartbeating recently. No row = no live
// apiserver, so no host could have heartbeated and no death verdict is fair.
func (q *Queries) OldestLiveApiserverStart(ctx context.Context, heartbeatAfter time.Time) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, oldestLiveApiserverStart, heartbeatAfter)
	var started_at time.Time
	err := row.Scan(&started_at)
	return started_at, err
}

const topologyDesiredRegions = `-- name: TopologyDesiredRegions :many
SELECT es.id AS es_id, dr.region, dr.replicas AS desired
FROM deployment_regions dr
JOIN deployments          d  ON d.id = dr.deployment_id AND d.is_current
JOIN environment_services es ON es.id = d.environment_service_id
JOIN environments         e  ON e.id = es.environment_id
WHERE ($1::text = '' OR e.project_name = $1)
  AND ($2::text = '' OR e.name = $2)
  AND ($3::text = '' OR dr.region = $3)
`

type TopologyDesiredRegionsParams struct {
	Project     string `json:"project"`
	Environment string `json:"environment"`
	Region      string `json:"region"`
}

type TopologyDesiredRegionsRow struct {
	EsID    uuid.UUID `json:"es_id"`
	Region  string    `json:"region"`
	Desired int32     `json:"desired"`
}

// Desired replica counts of the active commits, per region.
func (q *Queries) TopologyDesiredRegions(ctx context.Context, arg TopologyDesiredRegionsParams) ([]TopologyDesiredRegionsRow, error) {
	rows, err := q.db.QueryContext(ctx, topologyDesiredRegions, arg.Project, arg.Environment, arg.Region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopologyDesiredRegionsRow
	for rows.Next() {
		var i TopologyDesiredRegionsRow
		if err := rows.Scan(&i.EsID, &i.Region, &i.Desired); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topologyHosts = `-- name: TopologyHosts :many
SELECT id, region, hostname, cpu_millicores, mem_bytes, disk_bytes, labels, status, last_heartbeat, created_at FROM hosts
WHERE ($1::text = '' OR region = $1)
ORDER BY region, hostname
`

func (q *Queries) TopologyHosts(ctx context.Context, region string) ([]Host, error) {
	rows, err := q.db.QueryContext(ctx, topologyHosts, region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.Hostname,
			&i.CpuMillicores,
			&i.MemBytes,
			&i.DiskBytes,
			&i.Labels,
			&i.Status,
			&i.LastHeartbeat,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topologyReplicas = `-- name: TopologyReplicas :many
SELECT r.id, r.region, h.hostname, r.host_id, r.phase, r.healthy,
       r.desired_status, r.restart_count, r.last_exit_reason, r.updated_at,
       d.version AS dep_version, d.is_current, d.id AS deployment_id,
       es.id AS es_id
FROM replicas r
JOIN deployments          d  ON d.id = r.deployment_id
JOIN environment_services es ON es.id = d.environment_service_id
JOIN environments         e  ON e.id = es.environment_id
LEFT JOIN hosts h ON h.id = r.host_id
WHERE ($1::text = '' OR e.project_name = $1)
  AND ($2::text = '' OR e.name = $2)
  AND ($3::text = '' OR r.region = $3)
ORDER BY r.region, r.created_at
`

type TopologyReplicasParams struct {
	Project     string `json:"project"`
	Environment string `json:"environment"`
	Region      string `json:"region"`
}

type TopologyReplicasRow struct {
	ID             uuid.UUID      `json:"id"`
	Region         string         `json:"region"`
	Hostname       sql.NullString `json:"hostname"`
	HostID         uuid.NullUUID  `json:"host_id"`
	Phase          string         `json:"phase"`
	Healthy        bool           `json:"healthy"`
	DesiredStatus  string         `json:"desired_status"`
	RestartCount   int32          `json:"restart_count"`
	LastExitReason sql.NullString `json:"last_exit_reason"`
	UpdatedAt      time.Time      `json:"updated_at"`
	DepVersion     int32          `json:"dep_version"`
	IsCurrent      bool           `json:"is_current"`
	DeploymentID   uuid.UUID      `json:"deployment_id"`
	EsID           uuid.UUID      `json:"es_id"`
}

// Every replica of every version (not just the current one): a superseded or
// draining replica is exactly what the operator wants to watch disappear.
func (q *Queries) TopologyReplicas(ctx context.Context, arg TopologyReplicasParams) ([]TopologyReplicasRow, error) {
	rows, err := q.db.QueryContext(ctx, topologyReplicas, arg.Project, arg.Environment, arg.Region)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopologyReplicasRow
	for rows.Next() {
		var i TopologyReplicasRow
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.Hostname,
			&i.HostID,
			&i.Phase,
			&i.Healthy,
			&i.DesiredStatus,
			&i.RestartCount,
			&i.LastExitReason,
			&i.UpdatedAt,
			&i.DepVersion,
			&i.IsCurrent,
			&i.DeploymentID,
			&i.EsID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topologyServed = `-- name: TopologyServed :many
SELECT sr.environment_service_id, sr.region, sr.deployment_id,
       d.version AS dep_version, s.name AS service, e.name AS environment,
       sr.updated_at
FROM served_revisions sr
JOIN deployments          d  ON d.id = sr.deployment_id
JOIN environment_services es ON es.id = sr.environment_service_id
JOIN environments         e  ON e.id = es.environment_id
JOIN services             s  ON s.id = es.service_id
WHERE ($1::text = '' OR e.project_name = $1)
  AND ($2::text = '' OR e.name = $2)
ORDER BY e.name, s.name, sr.region
`

type TopologyServedParams struct {
	Project     string `json:"project"`
	Environment string `json:"environment"`
}

type TopologyServedRow struct {
	EnvironmentServiceID uuid.UUID `json:"environment_service_id"`
	Region               string    `json:"region"`
	DeploymentID         uuid.UUID `json:"deployment_id"`
	DepVersion           int32     `json:"dep_version"`
	Service              string    `json:"service"`
	Environment          string    `json:"environment"`
	UpdatedAt            time.Time `json:"updated_at"`
}

// Traffic pointers, so the UI can flag a slot still serving an older version.
func (q *Queries) TopologyServed(ctx context.Context, arg TopologyServedParams) ([]TopologyServedRow, error) {
	rows, err := q.db.QueryContext(ctx, topologyServed, arg.Project, arg.Environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopologyServedRow
	for rows.Next() {
		var i TopologyServedRow
		if err := rows.Scan(
			&i.EnvironmentServiceID,
			&i.Region,
			&i.DeploymentID,
			&i.DepVersion,
			&i.Service,
			&i.Environment,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topologyServices = `-- name: TopologyServices :many
SELECT es.id AS es_id, es.environment_id, s.name AS service, s.stateful,
       d.id AS deployment_id, d.version, d.status, d.image_ref, d.created_at,
       d.created_by, d.commit_message
FROM environment_services es
JOIN environments e ON e.id = es.environment_id
JOIN services     s ON s.id = es.service_id
LEFT JOIN deployments d ON d.environment_service_id = es.id AND d.is_current
WHERE ($1::text = '' OR e.project_name = $1)
  AND ($2::text = '' OR e.name = $2)
ORDER BY s.name
`

type TopologyServicesParams struct {
	Project     string `json:"project"`
	Environment string `json:"environment"`
}

type TopologyServicesRow struct {
	EsID          uuid.UUID      `json:"es_id"`
	EnvironmentID uuid.UUID      `json:"environment_id"`
	Service       string         `json:"service"`
	Stateful      bool           `json:"stateful"`
	DeploymentID  uuid.NullUUID  `json:"deployment_id"`
	Version       sql.NullInt32  `json:"version"`
	Status        sql.NullString `json:"status"`
	ImageRef      sql.NullString `json:"image_ref"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	CreatedBy     sql.NullString `json:"created_by"`
	CommitMessage sql.NullString `json:"commit_message"`
}

// One row per service binding plus its active deploy commit; the deployment
// join is LEFT so a bound-but-never-deployed service still appears.
func (q *Queries) TopologyServices(ctx context.Context, arg TopologyServicesParams) ([]TopologyServicesRow, error) {
	rows, err := q.db.QueryContext(ctx, topologyServices, arg.Project, arg.Environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopologyServicesRow
	for rows.Next() {
		var i TopologyServicesRow
		if err := rows.Scan(
			&i.EsID,
			&i.EnvironmentID,
			&i.Service,
			&i.Stateful,
			&i.DeploymentID,
			&i.Version,
			&i.Status,
			&i.ImageRef,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.CommitMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const uncordonHost = `-- name: UncordonHost :execrows
UPDATE hosts SET status = 'ready'
WHERE id = $1 AND status IN ('cordoned', 'draining')
`

// Operator hands a host back to scheduling; it returns as 'ready' and the next
// heartbeat (or its absence) corrects that within one sweep. Draining is
// included so an evacuation can be called off — without this a drained host
// had no way back except SQL.
func (q *Queries) UncordonHost(ctx context.Context, hostID uuid.UUID) (int64, error) {
	result, err := q.db.ExecContext(ctx, uncordonHost, hostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertApiserverInstance = `-- name: UpsertApiserverInstance :exec
INSERT INTO apiserver_instances (id, started_at, heartbeat_at)
VALUES ($1, $2, $3)
ON CONFLICT (id) DO UPDATE SET heartbeat_at = EXCLUDED.heartbeat_at
`

type UpsertApiserverInstanceParams struct {
	ID        uuid.UUID `json:"id"`
	StartedAt time.Time `json:"started_at"`
	Now       time.Time `json:"now"`
}

// Register-or-refresh in one statement: the heartbeat re-creates the row if
// it vanished (a dev schema rebuild while the apiserver kept running), so an
// instance can't silently drop out of the watchdog's grace computation.
// started_at is the instance's own start, never bumped by a refresh.
func (q *Queries) UpsertApiserverInstance(ctx context.Context, arg UpsertApiserverInstanceParams) error {
	_, err := q.db.ExecContext(ctx, upsertApiserverInstance, arg.ID, arg.StartedAt, arg.Now)
	return err
}
