// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (
	environment_service_id, version, is_current, image_ref,
	cpu_millicores, mem_bytes, env, healthcheck,
	drain_seconds, restart_max, commit_message, created_by
)
VALUES ($1, $2, true, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, environment_service_id, version, is_current, image_ref, cpu_millicores, mem_bytes, env, healthcheck, drain_seconds, restart_max, commit_message, created_by, status, created_at, progress_deadline
`

type CreateDeploymentParams struct {
	EnvironmentServiceID uuid.UUID       `json:"environment_service_id"`
	Version              int32           `json:"version"`
	ImageRef             string          `json:"image_ref"`
	CpuMillicores        int32           `json:"cpu_millicores"`
	MemBytes             int64           `json:"mem_bytes"`
	Env                  json.RawMessage `json:"env"`
	Healthcheck          json.RawMessage `json:"healthcheck"`
	DrainSeconds         int32           `json:"drain_seconds"`
	RestartMax           int32           `json:"restart_max"`
	CommitMessage        sql.NullString  `json:"commit_message"`
	CreatedBy            sql.NullString  `json:"created_by"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, createDeployment,
		arg.EnvironmentServiceID,
		arg.Version,
		arg.ImageRef,
		arg.CpuMillicores,
		arg.MemBytes,
		arg.Env,
		arg.Healthcheck,
		arg.DrainSeconds,
		arg.RestartMax,
		arg.CommitMessage,
		arg.CreatedBy,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.EnvironmentServiceID,
		&i.Version,
		&i.IsCurrent,
		&i.ImageRef,
		&i.CpuMillicores,
		&i.MemBytes,
		&i.Env,
		&i.Healthcheck,
		&i.DrainSeconds,
		&i.RestartMax,
		&i.CommitMessage,
		&i.CreatedBy,
		&i.Status,
		&i.CreatedAt,
		&i.ProgressDeadline,
	)
	return i, err
}

const currentDeploymentID = `-- name: CurrentDeploymentID :one
SELECT d.id
FROM deployments d
JOIN environment_services es ON es.id = d.environment_service_id
JOIN environments        e  ON e.id = es.environment_id
JOIN services            s  ON s.id = es.service_id
WHERE e.project_name = $1 AND e.name = $2
  AND s.name = $3 AND d.is_current
`

type CurrentDeploymentIDParams struct {
	ProjectName string `json:"project_name"`
	Environment string `json:"environment"`
	Service     string `json:"service"`
}

// CurrentDeploymentID resolves the (project, environment, service) triple to its
// active deploy commit — the deployment whose deployment_regions `scale`/`down`
// patch. No current commit (service never `up`ed) returns no rows, so callers
// can tell the user to deploy first.
func (q *Queries) CurrentDeploymentID(ctx context.Context, arg CurrentDeploymentIDParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, currentDeploymentID, arg.ProjectName, arg.Environment, arg.Service)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getCurrentDeployment = `-- name: GetCurrentDeployment :one

SELECT id, version FROM deployments
WHERE environment_service_id = $1 AND is_current
`

type GetCurrentDeploymentRow struct {
	ID      uuid.UUID `json:"id"`
	Version int32     `json:"version"`
}

// Rollback (`conductor rollback`): re-point is_current to an EXISTING older
// deployment, no rebuild. The target row's image_ref/env/sizing are reused
// verbatim — rollback never re-reads config.toml. The engine then converges to
// it like any other current deployment.
func (q *Queries) GetCurrentDeployment(ctx context.Context, environmentServiceID uuid.UUID) (GetCurrentDeploymentRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrentDeployment, environmentServiceID)
	var i GetCurrentDeploymentRow
	err := row.Scan(&i.ID, &i.Version)
	return i, err
}

const getDeploymentByVersion = `-- name: GetDeploymentByVersion :one
SELECT id, version FROM deployments
WHERE environment_service_id = $1 AND version = $2
`

type GetDeploymentByVersionParams struct {
	EnvironmentServiceID uuid.UUID `json:"environment_service_id"`
	Version              int32     `json:"version"`
}

type GetDeploymentByVersionRow struct {
	ID      uuid.UUID `json:"id"`
	Version int32     `json:"version"`
}

func (q *Queries) GetDeploymentByVersion(ctx context.Context, arg GetDeploymentByVersionParams) (GetDeploymentByVersionRow, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentByVersion, arg.EnvironmentServiceID, arg.Version)
	var i GetDeploymentByVersionRow
	err := row.Scan(&i.ID, &i.Version)
	return i, err
}

const getEnvironmentService = `-- name: GetEnvironmentService :one

SELECT es.id, es.source, s.id AS service_id, s.stateful
FROM environment_services es
JOIN environments e ON e.id = es.environment_id
JOIN services     s ON s.id = es.service_id
WHERE e.project_name = $1 AND e.name = $2 AND s.name = $3
`

type GetEnvironmentServiceParams struct {
	ProjectName string `json:"project_name"`
	Environment string `json:"environment"`
	Service     string `json:"service"`
}

type GetEnvironmentServiceRow struct {
	ID        uuid.UUID       `json:"id"`
	Source    json.RawMessage `json:"source"`
	ServiceID uuid.UUID       `json:"service_id"`
	Stateful  bool            `json:"stateful"`
}

// Queries backing `conductor up`: it deploys a single, already-existing service
// (created by `add`), reading its source then committing a new versioned
// deployment. Identity comes from the folder link / flags, never the spec file.
// GetEnvironmentService resolves the (project, environment, service) triple to
// the binding up needs: the environment_service id to hang the deployment off,
// the recorded source (repo/image), and whether the service is stateful.
func (q *Queries) GetEnvironmentService(ctx context.Context, arg GetEnvironmentServiceParams) (GetEnvironmentServiceRow, error) {
	row := q.db.QueryRowContext(ctx, getEnvironmentService, arg.ProjectName, arg.Environment, arg.Service)
	var i GetEnvironmentServiceRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ServiceID,
		&i.Stateful,
	)
	return i, err
}

const markCurrentRolledBack = `-- name: MarkCurrentRolledBack :exec
UPDATE deployments
SET is_current = false, status = 'rolledback'
WHERE environment_service_id = $1 AND is_current
`

func (q *Queries) MarkCurrentRolledBack(ctx context.Context, environmentServiceID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markCurrentRolledBack, environmentServiceID)
	return err
}

const nextDeploymentVersion = `-- name: NextDeploymentVersion :one
SELECT (COALESCE(MAX(version), 0) + 1)::int AS next_version
FROM deployments
WHERE environment_service_id = $1
`

// NextDeploymentVersion is the per-service-env monotonic counter (§13). Cast
// keeps sqlc from typing the COALESCE+1 as a nullable interface.
func (q *Queries) NextDeploymentVersion(ctx context.Context, environmentServiceID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, nextDeploymentVersion, environmentServiceID)
	var next_version int32
	err := row.Scan(&next_version)
	return next_version, err
}

const previousDeploymentVersion = `-- name: PreviousDeploymentVersion :one
SELECT version FROM deployments
WHERE environment_service_id = $1 AND version < $2
ORDER BY version DESC
LIMIT 1
`

type PreviousDeploymentVersionParams struct {
	EnvironmentServiceID uuid.UUID `json:"environment_service_id"`
	Before               int32     `json:"before"`
}

// PreviousDeploymentVersion is the highest version below @before — the default
// rollback target ("the one before the current one"). No row ⇒ nothing earlier.
func (q *Queries) PreviousDeploymentVersion(ctx context.Context, arg PreviousDeploymentVersionParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, previousDeploymentVersion, arg.EnvironmentServiceID, arg.Before)
	var version int32
	err := row.Scan(&version)
	return version, err
}

const setDeploymentCurrent = `-- name: SetDeploymentCurrent :exec
UPDATE deployments
SET is_current = true, status = 'pending'
WHERE id = $1
`

// SetDeploymentCurrent promotes a past version back to current. status returns to
// 'pending' so the engine re-runs the rollout toward it. Run after
// MarkCurrentRolledBack in the same tx so the one-current partial index never trips.
func (q *Queries) SetDeploymentCurrent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setDeploymentCurrent, id)
	return err
}

const setDeploymentRegion = `-- name: SetDeploymentRegion :exec
INSERT INTO deployment_regions (deployment_id, region, replicas)
VALUES ($1, $2, $3)
ON CONFLICT (deployment_id, region) DO UPDATE SET replicas = EXCLUDED.replicas
`

type SetDeploymentRegionParams struct {
	DeploymentID uuid.UUID `json:"deployment_id"`
	Region       string    `json:"region"`
	Replicas     int32     `json:"replicas"`
}

func (q *Queries) SetDeploymentRegion(ctx context.Context, arg SetDeploymentRegionParams) error {
	_, err := q.db.ExecContext(ctx, setDeploymentRegion, arg.DeploymentID, arg.Region, arg.Replicas)
	return err
}

const supersedeCurrentDeployments = `-- name: SupersedeCurrentDeployments :exec
UPDATE deployments
SET is_current = false, status = 'superseded'
WHERE environment_service_id = $1 AND is_current
`

// SupersedeCurrentDeployments clears the active commit before a new one is
// inserted as current, so the one-current-per-service partial unique index
// never trips. Runs in the same tx as the insert.
func (q *Queries) SupersedeCurrentDeployments(ctx context.Context, environmentServiceID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, supersedeCurrentDeployments, environmentServiceID)
	return err
}

const zeroDeploymentRegions = `-- name: ZeroDeploymentRegions :exec
UPDATE deployment_regions SET replicas = 0
WHERE deployment_id = $1
`

// ZeroDeploymentRegions drives `conductor down`: every region the current commit
// targets goes to zero replicas, so the reconcile loop reaps the compute while
// leaving the deployment (and any volumes) in place.
func (q *Queries) ZeroDeploymentRegions(ctx context.Context, deploymentID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, zeroDeploymentRegions, deploymentID)
	return err
}
