// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Deployment struct {
	ID                   uuid.UUID       `json:"id"`
	EnvironmentServiceID uuid.UUID       `json:"environment_service_id"`
	Version              int32           `json:"version"`
	IsCurrent            bool            `json:"is_current"`
	ImageRef             string          `json:"image_ref"`
	CpuMillicores        int32           `json:"cpu_millicores"`
	MemBytes             int64           `json:"mem_bytes"`
	Env                  json.RawMessage `json:"env"`
	Healthcheck          json.RawMessage `json:"healthcheck"`
	DrainSeconds         int32           `json:"drain_seconds"`
	RestartMax           int32           `json:"restart_max"`
	CommitMessage        sql.NullString  `json:"commit_message"`
	CreatedBy            sql.NullString  `json:"created_by"`
	Status               string          `json:"status"`
	CreatedAt            time.Time       `json:"created_at"`
}

type DeploymentRegion struct {
	DeploymentID uuid.UUID `json:"deployment_id"`
	Region       string    `json:"region"`
	Replicas     int32     `json:"replicas"`
}

type Environment struct {
	ID          uuid.UUID `json:"id"`
	ProjectName string    `json:"project_name"`
	Name        string    `json:"name"`
	CreatedAt   time.Time `json:"created_at"`
}

type EnvironmentService struct {
	ID            uuid.UUID       `json:"id"`
	EnvironmentID uuid.UUID       `json:"environment_id"`
	ServiceID     uuid.UUID       `json:"service_id"`
	Source        json.RawMessage `json:"source"`
}

type Host struct {
	ID            uuid.UUID       `json:"id"`
	Region        string          `json:"region"`
	Hostname      string          `json:"hostname"`
	CpuMillicores int32           `json:"cpu_millicores"`
	MemBytes      int64           `json:"mem_bytes"`
	DiskBytes     int64           `json:"disk_bytes"`
	Labels        json.RawMessage `json:"labels"`
	Status        string          `json:"status"`
	LastHeartbeat sql.NullTime    `json:"last_heartbeat"`
	Revision      int64           `json:"revision"`
	CreatedAt     time.Time       `json:"created_at"`
}

type Project struct {
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Region struct {
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Replica struct {
	ID             uuid.UUID      `json:"id"`
	DeploymentID   uuid.UUID      `json:"deployment_id"`
	Region         string         `json:"region"`
	HostID         uuid.NullUUID  `json:"host_id"`
	VolumeID       uuid.NullUUID  `json:"volume_id"`
	CpuMillicores  int32          `json:"cpu_millicores"`
	MemBytes       int64          `json:"mem_bytes"`
	AllocReason    sql.NullString `json:"alloc_reason"`
	DesiredStatus  string         `json:"desired_status"`
	Phase          string         `json:"phase"`
	Healthy        bool           `json:"healthy"`
	RestartCount   int32          `json:"restart_count"`
	LastExitReason sql.NullString `json:"last_exit_reason"`
	Revision       int64          `json:"revision"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

type Service struct {
	ID          uuid.UUID `json:"id"`
	ProjectName string    `json:"project_name"`
	Name        string    `json:"name"`
	Stateful    bool      `json:"stateful"`
	CreatedAt   time.Time `json:"created_at"`
}

type Volume struct {
	ID                uuid.UUID     `json:"id"`
	ServiceID         uuid.UUID     `json:"service_id"`
	Name              string        `json:"name"`
	MountPath         string        `json:"mount_path"`
	Region            string        `json:"region"`
	HostID            uuid.NullUUID `json:"host_id"`
	Backing           string        `json:"backing"`
	DesiredSizeBytes  int64         `json:"desired_size_bytes"`
	ObservedSizeBytes sql.NullInt64 `json:"observed_size_bytes"`
	Status            string        `json:"status"`
	Revision          int64         `json:"revision"`
	CreatedAt         time.Time     `json:"created_at"`
}

type VolumeLease struct {
	VolumeID   uuid.UUID `json:"volume_id"`
	ReplicaID  uuid.UUID `json:"replica_id"`
	ExpiresAt  time.Time `json:"expires_at"`
	AcquiredAt time.Time `json:"acquired_at"`
}
