// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const addServiceToEnvironment = `-- name: AddServiceToEnvironment :one
INSERT INTO environment_services (environment_id, service_id, source)
VALUES ($1, $2, $3)
RETURNING id, environment_id, service_id, source
`

type AddServiceToEnvironmentParams struct {
	EnvironmentID uuid.UUID       `json:"environment_id"`
	ServiceID     uuid.UUID       `json:"service_id"`
	Source        json.RawMessage `json:"source"`
}

func (q *Queries) AddServiceToEnvironment(ctx context.Context, arg AddServiceToEnvironmentParams) (EnvironmentService, error) {
	row := q.db.QueryRowContext(ctx, addServiceToEnvironment, arg.EnvironmentID, arg.ServiceID, arg.Source)
	var i EnvironmentService
	err := row.Scan(
		&i.ID,
		&i.EnvironmentID,
		&i.ServiceID,
		&i.Source,
	)
	return i, err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (project_name, name)
VALUES ($1, $2)
RETURNING id, project_name, name, created_at
`

type CreateEnvironmentParams struct {
	ProjectName string `json:"project_name"`
	Name        string `json:"name"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRowContext(ctx, createEnvironment, arg.ProjectName, arg.Name)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.ProjectName,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name)
VALUES ($1)
RETURNING name, created_at
`

func (q *Queries) CreateProject(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, name)
	var i Project
	err := row.Scan(&i.Name, &i.CreatedAt)
	return i, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (project_name, name, stateful)
VALUES ($1, $2, $3)
RETURNING id, project_name, name, stateful, created_at
`

type CreateServiceParams struct {
	ProjectName string `json:"project_name"`
	Name        string `json:"name"`
	Stateful    bool   `json:"stateful"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, createService, arg.ProjectName, arg.Name, arg.Stateful)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ProjectName,
		&i.Name,
		&i.Stateful,
		&i.CreatedAt,
	)
	return i, err
}
