// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconcile.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const acquireVolumeLease = `-- name: AcquireVolumeLease :execrows
INSERT INTO volume_leases (volume_id, replica_id, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (volume_id) DO UPDATE
	SET replica_id  = EXCLUDED.replica_id,
	    expires_at  = EXCLUDED.expires_at,
	    acquired_at = now()
WHERE volume_leases.expires_at <= now()
   OR volume_leases.replica_id = EXCLUDED.replica_id
`

type AcquireVolumeLeaseParams struct {
	VolumeID  uuid.UUID `json:"volume_id"`
	ReplicaID uuid.UUID `json:"replica_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Take (or renew) the single-writer lease. The PK on volume_id is the invariant;
// the upsert only overwrites a lease that has expired or that this same replica
// already holds, so a different live holder yields rows-affected = 0.
func (q *Queries) AcquireVolumeLease(ctx context.Context, arg AcquireVolumeLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acquireVolumeLease, arg.VolumeID, arg.ReplicaID, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const activeVolumeLease = `-- name: ActiveVolumeLease :one

SELECT volume_id, replica_id, expires_at, acquired_at FROM volume_leases
WHERE volume_id = $1 AND expires_at > now()
`

// Engine reconcile-path writes. These are the operations that must commit
// together (see storage.ReconcileTx); the read/decide queries the loop runs
// beforehand live elsewhere.
// The live lease on a volume, if any. No row (sql.ErrNoRows) means the volume is
// free to claim. Used inside the tx to close the TOCTOU gap before acquiring.
func (q *Queries) ActiveVolumeLease(ctx context.Context, volumeID uuid.UUID) (VolumeLease, error) {
	row := q.db.QueryRowContext(ctx, activeVolumeLease, volumeID)
	var i VolumeLease
	err := row.Scan(
		&i.VolumeID,
		&i.ReplicaID,
		&i.ExpiresAt,
		&i.AcquiredAt,
	)
	return i, err
}

const assignVolumeHost = `-- name: AssignVolumeHost :exec
UPDATE volumes
SET host_id = $2, status = 'attached', revision = revision + 1
WHERE id = $1
`

type AssignVolumeHostParams struct {
	ID     uuid.UUID     `json:"id"`
	HostID uuid.NullUUID `json:"host_id"`
}

// Bind a volume to the host its replica landed on. Bumps revision so a stale
// reader detects the move.
func (q *Queries) AssignVolumeHost(ctx context.Context, arg AssignVolumeHostParams) error {
	_, err := q.db.ExecContext(ctx, assignVolumeHost, arg.ID, arg.HostID)
	return err
}

const createReplica = `-- name: CreateReplica :one
INSERT INTO replicas (deployment_id, region, cpu_millicores, mem_bytes, alloc_reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, deployment_id, region, host_id, volume_id, cpu_millicores, mem_bytes, alloc_reason, desired_status, phase, healthy, restart_count, last_exit_reason, revision, created_at, updated_at
`

type CreateReplicaParams struct {
	DeploymentID  uuid.UUID      `json:"deployment_id"`
	Region        string         `json:"region"`
	CpuMillicores int32          `json:"cpu_millicores"`
	MemBytes      int64          `json:"mem_bytes"`
	AllocReason   sql.NullString `json:"alloc_reason"`
}

// Schedule a replica for a (deployment, region). Host/volume are bound after
// placement is decided; phase/desired_status take their column defaults.
func (q *Queries) CreateReplica(ctx context.Context, arg CreateReplicaParams) (Replica, error) {
	row := q.db.QueryRowContext(ctx, createReplica,
		arg.DeploymentID,
		arg.Region,
		arg.CpuMillicores,
		arg.MemBytes,
		arg.AllocReason,
	)
	var i Replica
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.Region,
		&i.HostID,
		&i.VolumeID,
		&i.CpuMillicores,
		&i.MemBytes,
		&i.AllocReason,
		&i.DesiredStatus,
		&i.Phase,
		&i.Healthy,
		&i.RestartCount,
		&i.LastExitReason,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteReplica = `-- name: DeleteReplica :exec
DELETE FROM replicas WHERE id = $1
`

// Reclaim a replica row.
func (q *Queries) DeleteReplica(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReplica, id)
	return err
}

const releaseVolumeLease = `-- name: ReleaseVolumeLease :exec
DELETE FROM volume_leases WHERE volume_id = $1
`

// Drop a lease so a freed volume is immediately re-leasable.
func (q *Queries) ReleaseVolumeLease(ctx context.Context, volumeID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, releaseVolumeLease, volumeID)
	return err
}

const reserveReplicaOnHost = `-- name: ReserveReplicaOnHost :execrows
WITH bump AS (
	UPDATE hosts SET revision = hosts.revision + 1
	WHERE hosts.id = $2 AND hosts.revision = $3
	RETURNING hosts.id
)
UPDATE replicas
SET host_id = $2, phase = 'scheduling'
WHERE replicas.id = $1 AND EXISTS (SELECT 1 FROM bump)
`

type ReserveReplicaOnHostParams struct {
	ID       uuid.UUID     `json:"id"`
	HostID   uuid.NullUUID `json:"host_id"`
	Revision int64         `json:"revision"`
}

// Reserve a replica onto a host under optimistic concurrency: the host's
// revision must still equal what the scheduler read while bin-packing, or the
// host filled up under us and the whole placement must roll back. The CTE bumps
// the host revision (the CAS) and the replica update only lands if that bump
// matched — so rows-affected = 0 signals a lost race.
func (q *Queries) ReserveReplicaOnHost(ctx context.Context, arg ReserveReplicaOnHostParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reserveReplicaOnHost, arg.ID, arg.HostID, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setReplicaDesiredStatus = `-- name: SetReplicaDesiredStatus :exec
UPDATE replicas SET desired_status = $2 WHERE id = $1
`

type SetReplicaDesiredStatusParams struct {
	ID            uuid.UUID `json:"id"`
	DesiredStatus string    `json:"desired_status"`
}

// Flip a replica's desired status (e.g. to 'running' once its lease is held, or
// 'stopped' to begin reclaim).
func (q *Queries) SetReplicaDesiredStatus(ctx context.Context, arg SetReplicaDesiredStatusParams) error {
	_, err := q.db.ExecContext(ctx, setReplicaDesiredStatus, arg.ID, arg.DesiredStatus)
	return err
}
