// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconcile.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const acquireVolumeLease = `-- name: AcquireVolumeLease :execrows
INSERT INTO volume_leases (volume_id, replica_id, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (volume_id) DO UPDATE
	SET replica_id  = EXCLUDED.replica_id,
	    expires_at  = EXCLUDED.expires_at,
	    acquired_at = now()
WHERE volume_leases.expires_at <= now()
   OR volume_leases.replica_id = EXCLUDED.replica_id
`

type AcquireVolumeLeaseParams struct {
	VolumeID  uuid.UUID `json:"volume_id"`
	ReplicaID uuid.UUID `json:"replica_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Take (or renew) the single-writer lease. The PK on volume_id is the invariant;
// the upsert only overwrites a lease that has expired or that this same replica
// already holds, so a different live holder yields rows-affected = 0.
func (q *Queries) AcquireVolumeLease(ctx context.Context, arg AcquireVolumeLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, acquireVolumeLease, arg.VolumeID, arg.ReplicaID, arg.ExpiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const activeVolumeLease = `-- name: ActiveVolumeLease :one

SELECT volume_id, replica_id, expires_at, acquired_at FROM volume_leases
WHERE volume_id = $1 AND expires_at > now()
`

// Engine reconcile-path writes. These are the operations that must commit
// together (see storage.ReconcileTx); the read/decide queries the loop runs
// beforehand live elsewhere.
// The live lease on a volume, if any. No row (sql.ErrNoRows) means the volume is
// free to claim. Used inside the tx to close the TOCTOU gap before acquiring.
func (q *Queries) ActiveVolumeLease(ctx context.Context, volumeID uuid.UUID) (VolumeLease, error) {
	row := q.db.QueryRowContext(ctx, activeVolumeLease, volumeID)
	var i VolumeLease
	err := row.Scan(
		&i.VolumeID,
		&i.ReplicaID,
		&i.ExpiresAt,
		&i.AcquiredAt,
	)
	return i, err
}

const assignVolumeHost = `-- name: AssignVolumeHost :exec
UPDATE volumes
SET host_id = $2, status = 'attached'
WHERE id = $1
`

type AssignVolumeHostParams struct {
	ID     uuid.UUID     `json:"id"`
	HostID uuid.NullUUID `json:"host_id"`
}

// Bind a volume to the host its replica landed on.
func (q *Queries) AssignVolumeHost(ctx context.Context, arg AssignVolumeHostParams) error {
	_, err := q.db.ExecContext(ctx, assignVolumeHost, arg.ID, arg.HostID)
	return err
}

const createReplica = `-- name: CreateReplica :one
INSERT INTO replicas (deployment_id, region, cpu_millicores, mem_bytes, alloc_reason, volume_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, deployment_id, region, host_id, volume_id, cpu_millicores, mem_bytes, alloc_reason, desired_status, phase, healthy, restart_count, last_exit_reason, revision, created_at, updated_at, drained_at, health_checks_passed_at
`

type CreateReplicaParams struct {
	DeploymentID  uuid.UUID      `json:"deployment_id"`
	Region        string         `json:"region"`
	CpuMillicores int32          `json:"cpu_millicores"`
	MemBytes      int64          `json:"mem_bytes"`
	AllocReason   sql.NullString `json:"alloc_reason"`
	VolumeID      uuid.NullUUID  `json:"volume_id"`
}

// Schedule a replica for a (deployment, region). The host is bound after
// placement is decided; phase/desired_status take their column defaults. A
// stateful replica binds its volume here at mint time — placement then pins it
// to the volume's host and the lease acquires against it.
func (q *Queries) CreateReplica(ctx context.Context, arg CreateReplicaParams) (Replica, error) {
	row := q.db.QueryRowContext(ctx, createReplica,
		arg.DeploymentID,
		arg.Region,
		arg.CpuMillicores,
		arg.MemBytes,
		arg.AllocReason,
		arg.VolumeID,
	)
	var i Replica
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.Region,
		&i.HostID,
		&i.VolumeID,
		&i.CpuMillicores,
		&i.MemBytes,
		&i.AllocReason,
		&i.DesiredStatus,
		&i.Phase,
		&i.Healthy,
		&i.RestartCount,
		&i.LastExitReason,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DrainedAt,
		&i.HealthChecksPassedAt,
	)
	return i, err
}

const deleteReplica = `-- name: DeleteReplica :exec
DELETE FROM replicas WHERE id = $1
`

// Reclaim a replica row.
func (q *Queries) DeleteReplica(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteReplica, id)
	return err
}

const getServedRevision = `-- name: GetServedRevision :one
SELECT environment_service_id, region, deployment_id, updated_at FROM served_revisions
WHERE environment_service_id = $1 AND region = $2
`

type GetServedRevisionParams struct {
	EnvironmentServiceID uuid.UUID `json:"environment_service_id"`
	Region               string    `json:"region"`
}

// The deployment a slot's traffic currently points at (router / status reads).
func (q *Queries) GetServedRevision(ctx context.Context, arg GetServedRevisionParams) (ServedRevision, error) {
	row := q.db.QueryRowContext(ctx, getServedRevision, arg.EnvironmentServiceID, arg.Region)
	var i ServedRevision
	err := row.Scan(
		&i.EnvironmentServiceID,
		&i.Region,
		&i.DeploymentID,
		&i.UpdatedAt,
	)
	return i, err
}

const releaseVolumeLease = `-- name: ReleaseVolumeLease :exec
DELETE FROM volume_leases WHERE volume_id = $1
`

// Drop a lease so a freed volume is immediately re-leasable.
func (q *Queries) ReleaseVolumeLease(ctx context.Context, volumeID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, releaseVolumeLease, volumeID)
	return err
}

const reserveReplicaOnHost = `-- name: ReserveReplicaOnHost :execrows
UPDATE replicas
SET host_id = $2, phase = 'scheduling'
WHERE replicas.id = $1
  AND EXISTS (
    SELECT 1 FROM hosts h
    WHERE h.id = $2
      AND h.status = 'ready'
      AND (SELECT coalesce(sum(r.cpu_millicores), 0) FROM replicas r
           WHERE r.host_id = h.id AND r.phase NOT IN ('reaped', 'failed'))
          + replicas.cpu_millicores <= h.cpu_millicores
      AND (SELECT coalesce(sum(r.mem_bytes), 0) FROM replicas r
           WHERE r.host_id = h.id AND r.phase NOT IN ('reaped', 'failed'))
          + replicas.mem_bytes <= h.mem_bytes
  )
`

type ReserveReplicaOnHostParams struct {
	ID     uuid.UUID     `json:"id"`
	HostID uuid.NullUUID `json:"host_id"`
}

// Reserve a replica onto a host — the predicated reservation. The WHERE
// carries the real invariant (host ready, capacity still sufficient in every
// dimension) instead of a version proxy: the old hosts.revision CAS aborted on
// ANY occupancy change, so two same-pass placements onto one half-empty host
// conflicted even when both fit. Summing live replicas makes the check
// drift-proof — there is no reserved counter to desync; the rows ARE the
// ledger. The replica's own row supplies the demand.
//
// Failed replicas are excluded from the sum: a crashed container consumes
// nothing, and reapFailedOutgoing deletes the row on its own clock — counting
// it would block a re-place exactly when one is needed. (The in-memory placer
// counts them anyway; being more conservative than the belt is safe.)
//
// rows-affected = 0 means the replica vanished, the host stopped being ready,
// or the demand genuinely no longer fits — all the same answer: drop the
// placement, next tick recomputes. Concurrency note: the check-and-write is
// atomic against writers of THIS replica row; placement itself stays
// single-writer (one engine), which is what makes the uncounted gap between
// two concurrent reservations onto one host a non-case.
func (q *Queries) ReserveReplicaOnHost(ctx context.Context, arg ReserveReplicaOnHostParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reserveReplicaOnHost, arg.ID, arg.HostID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setDeploymentStatus = `-- name: SetDeploymentStatus :exec
UPDATE deployments SET status = $2 WHERE id = $1
`

type SetDeploymentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

// Flip a deployment's lifecycle status (failed on crash-loop/stall, active on
// rollout completion). Unconditional: the Reconciler is the only status writer
// on the reconcile path, and re-asserting the same status is harmless.
func (q *Queries) SetDeploymentStatus(ctx context.Context, arg SetDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, setDeploymentStatus, arg.ID, arg.Status)
	return err
}

const setReplicaDesiredStatus = `-- name: SetReplicaDesiredStatus :exec
UPDATE replicas SET desired_status = $2 WHERE id = $1
`

type SetReplicaDesiredStatusParams struct {
	ID            uuid.UUID `json:"id"`
	DesiredStatus string    `json:"desired_status"`
}

// Flip a replica's desired status (e.g. to 'running' once its lease is held, or
// 'stopped' to begin reclaim).
func (q *Queries) SetReplicaDesiredStatus(ctx context.Context, arg SetReplicaDesiredStatusParams) error {
	_, err := q.db.ExecContext(ctx, setReplicaDesiredStatus, arg.ID, arg.DesiredStatus)
	return err
}

const setReplicaPhase = `-- name: SetReplicaPhase :execrows
UPDATE replicas
SET phase = $2,
    drained_at = CASE WHEN $2 = 'draining' THEN now() ELSE drained_at END,
    revision = revision + 1
WHERE id = $1 AND revision = $3
`

type SetReplicaPhaseParams struct {
	ID       uuid.UUID `json:"id"`
	Phase    string    `json:"phase"`
	Revision int64     `json:"revision"`
}

// Advance a replica's lifecycle phase under optimistic concurrency: the write
// only lands if revision still matches what the loop read, so a phase decided
// against stale observed state (the Sensor moved it meanwhile) is dropped rather
// than clobbering. rows-affected = 0 signals the lost race.
// Stamps drained_at when (and only when) entering draining, so the drain-window
// rule can reap at drained_at + drain_seconds; other transitions leave it intact.
func (q *Queries) SetReplicaPhase(ctx context.Context, arg SetReplicaPhaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setReplicaPhase, arg.ID, arg.Phase, arg.Revision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setServedRevision = `-- name: SetServedRevision :exec
INSERT INTO served_revisions (environment_service_id, region, deployment_id)
VALUES ($1, $2, $3)
ON CONFLICT (environment_service_id, region) DO UPDATE
	SET deployment_id = EXCLUDED.deployment_id,
	    updated_at    = now()
`

type SetServedRevisionParams struct {
	EnvironmentServiceID uuid.UUID `json:"environment_service_id"`
	Region               string    `json:"region"`
	DeploymentID         uuid.UUID `json:"deployment_id"`
}

// Flip the slot's traffic switch to a new deployment. Runs in the same tx as
// the outgoing drain batch so the shift is atomic with retiring the old side.
func (q *Queries) SetServedRevision(ctx context.Context, arg SetServedRevisionParams) error {
	_, err := q.db.ExecContext(ctx, setServedRevision, arg.EnvironmentServiceID, arg.Region, arg.DeploymentID)
	return err
}
