// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sensor.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const completeDrainedHosts = `-- name: CompleteDrainedHosts :many
UPDATE hosts SET status = 'cordoned', drain_started_at = NULL
WHERE status = 'draining'
  AND NOT EXISTS (
      SELECT 1 FROM replicas r
      WHERE r.host_id = hosts.id
        AND r.volume_id IS NULL
        AND r.phase NOT IN ('reaped', 'failed')
  )
RETURNING id, region, hostname, cpu_millicores, mem_bytes, disk_bytes, labels, status, last_heartbeat, created_at, host_healthy, drain_started_at
`

// A drain is done when nothing that can leave is left: stateless replicas
// gone past reap (a drained one still runs until the window elapses, so it
// counts). Stateful replicas are pinned to their volume and never move, so
// they don't hold the drain open — the host lands in 'cordoned' with them
// still on it, for the operator to migrate by hand. Fleet-wide, one statement.
func (q *Queries) CompleteDrainedHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.QueryContext(ctx, completeDrainedHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.Hostname,
			&i.CpuMillicores,
			&i.MemBytes,
			&i.DiskBytes,
			&i.Labels,
			&i.Status,
			&i.LastHeartbeat,
			&i.CreatedAt,
			&i.HostHealthy,
			&i.DrainStartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentHosts = `-- name: ListAgentHosts :many
SELECT id, region, hostname, cpu_millicores, mem_bytes, disk_bytes, labels, status, last_heartbeat, created_at, host_healthy, drain_started_at FROM hosts
`

// Agent discovery: every host an agent could run on. Health and status are
// deliberately ignored — an agent lives on the machine regardless, and an
// unhealthy host's agent must be able to enroll and heartbeat or a demoted
// host could never heal back.
func (q *Queries) ListAgentHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.QueryContext(ctx, listAgentHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.Hostname,
			&i.CpuMillicores,
			&i.MemBytes,
			&i.DiskBytes,
			&i.Labels,
			&i.Status,
			&i.LastHeartbeat,
			&i.CreatedAt,
			&i.HostHealthy,
			&i.DrainStartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeadHosts = `-- name: ListDeadHosts :many
SELECT hosts.id, hosts.region, hosts.hostname, hosts.cpu_millicores, hosts.mem_bytes, hosts.disk_bytes, hosts.labels, hosts.status, hosts.last_heartbeat, hosts.created_at, hosts.host_healthy, hosts.drain_started_at FROM hosts
WHERE last_heartbeat IS NOT NULL
  AND last_heartbeat < $1
  AND EXISTS (
      SELECT 1 FROM replicas r
      WHERE r.host_id = hosts.id
        AND r.phase NOT IN ('reaped', 'failed')
        AND r.drained_at IS NULL
  )
`

// Second staleness threshold: hosts silent long enough to be declared dead,
// listed for MarkHostDown. Operator status is irrelevant here: a draining or
// cordoned host that dies still holds replicas nobody else will free.
// The EXISTS keeps the list level-triggered and self-quieting: once a host's
// replicas are freed it stops matching, so an already-downed host isn't
// re-marked every sweep.
func (q *Queries) ListDeadHosts(ctx context.Context, lastHeartbeatBefore sql.NullTime) ([]Host, error) {
	rows, err := q.db.QueryContext(ctx, listDeadHosts, lastHeartbeatBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.Hostname,
			&i.CpuMillicores,
			&i.MemBytes,
			&i.DiskBytes,
			&i.Labels,
			&i.Status,
			&i.LastHeartbeat,
			&i.CreatedAt,
			&i.HostHealthy,
			&i.DrainStartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplicasByHost = `-- name: ListReplicasByHost :many
SELECT id, deployment_id, region, host_id, volume_id, cpu_millicores, mem_bytes, alloc_reason, desired_status, phase, healthy, restart_count, last_exit_reason, revision, created_at, updated_at, drained_at, health_checks_passed_at FROM replicas
WHERE host_id = $1 AND phase NOT IN ('reaped', 'failed')
`

// The replicas a host agent is responsible for driving (start scheduling,
// drain draining, report the rest). Failed rows are left out on purpose: the
// agent never learns the word "failed" — a frozen replica simply vanishes from
// its list, which the agent treats as "tear the container down", and the row
// stays in the database holding the deployment's slot until an operator acts.
func (q *Queries) ListReplicasByHost(ctx context.Context, hostID uuid.NullUUID) ([]Replica, error) {
	rows, err := q.db.QueryContext(ctx, listReplicasByHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Replica
	for rows.Next() {
		var i Replica
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Region,
			&i.HostID,
			&i.VolumeID,
			&i.CpuMillicores,
			&i.MemBytes,
			&i.AllocReason,
			&i.DesiredStatus,
			&i.Phase,
			&i.Healthy,
			&i.RestartCount,
			&i.LastExitReason,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DrainedAt,
			&i.HealthChecksPassedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStalledDrains = `-- name: ListStalledDrains :many
SELECT id, region, hostname, cpu_millicores, mem_bytes, disk_bytes, labels, status, last_heartbeat, created_at, host_healthy, drain_started_at FROM hosts
WHERE status = 'draining' AND drain_started_at < $1
ORDER BY drain_started_at
`

// Drains in flight longer than the caller's window: nothing acts on them,
// the sweep only makes the stall visible (a region out of capacity, a
// replacement that never turns healthy).
func (q *Queries) ListStalledDrains(ctx context.Context, startedBefore sql.NullTime) ([]Host, error) {
	rows, err := q.db.QueryContext(ctx, listStalledDrains, startedBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.Hostname,
			&i.CpuMillicores,
			&i.MemBytes,
			&i.DiskBytes,
			&i.Labels,
			&i.Status,
			&i.LastHeartbeat,
			&i.CreatedAt,
			&i.HostHealthy,
			&i.DrainStartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumesByHost = `-- name: ListVolumesByHost :many
SELECT id, name, mount_path, region, host_id, backing, desired_size_bytes, observed_size_bytes, status, created_at, previous_desired_size_bytes, environment_service_id FROM volumes
WHERE host_id = $1
ORDER BY id
`

// The disks a host agent is responsible for: create on first sight, grow when
// the control plane's target exceeds what's on disk, delete when gone. The
// size the agent should converge to is derived in the AgentAPI from status +
// desired/observed, so the whole row travels.
func (q *Queries) ListVolumesByHost(ctx context.Context, hostID uuid.NullUUID) ([]Volume, error) {
	rows, err := q.db.QueryContext(ctx, listVolumesByHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Volume
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MountPath,
			&i.Region,
			&i.HostID,
			&i.Backing,
			&i.DesiredSizeBytes,
			&i.ObservedSizeBytes,
			&i.Status,
			&i.CreatedAt,
			&i.PreviousDesiredSizeBytes,
			&i.EnvironmentServiceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markHostDown = `-- name: MarkHostDown :exec
WITH downed AS (
    UPDATE hosts SET host_healthy = false
    WHERE hosts.id = $1
      AND hosts.last_heartbeat IS NOT NULL
      AND hosts.last_heartbeat < $2
    RETURNING hosts.id
)
UPDATE replicas
SET host_id = NULL,
    healthy = false,
    phase = 'replacing',
    revision = revision + 1
WHERE host_id IN (SELECT id FROM downed)
  AND phase NOT IN ('reaped', 'failed')
  AND drained_at IS NULL
`

type MarkHostDownParams struct {
	HostID              uuid.UUID    `json:"host_id"`
	LastHeartbeatBefore sql.NullTime `json:"last_heartbeat_before"`
}

// Take a dead host out of scheduling and free its replicas in one atomic
// statement: a downed host with still-bound replicas is invisible to the
// Reconciler (anyHostlessReplicas keys on host_id IS NULL), so the two writes
// must never be observable apart. Replicas drop to hostless 'replacing' — the
// placer reads it as a replacement (skips the headroom reserve), and the
// observation guard below owns it, so a partitioned-but-alive agent can't
// resurrect a freed replica. Already-draining replicas keep their host
// binding: they're retiring on the drain window regardless, and unassigning
// them would erase the drain state. status is not touched: a draining host
// that dies is still draining when it comes back.
// The WHERE re-asserts staleness: a heartbeat landing between the sweep's
// ListDeadHosts and this write refreshes last_heartbeat, so the recovered
// host matches nothing and keeps its replicas — downing rides on the
// predicate, not on the sweep's possibly-stale list.
func (q *Queries) MarkHostDown(ctx context.Context, arg MarkHostDownParams) error {
	_, err := q.db.ExecContext(ctx, markHostDown, arg.HostID, arg.LastHeartbeatBefore)
	return err
}

const markStaleHostsUnhealthy = `-- name: MarkStaleHostsUnhealthy :execrows
UPDATE hosts
SET host_healthy = false
WHERE host_healthy
  AND last_heartbeat IS NOT NULL
  AND last_heartbeat < $1
`

// First staleness threshold: a briefly-silent host stops receiving NEW work
// (the placer's ledger holds healthy hosts only) but keeps its replicas —
// cheap and reversible, the next heartbeat flips it straight back. One
// fleet-wide statement, no per-host loop. NULL last_heartbeat is excluded: a
// host that never enrolled an agent (seeded dev fleet) isn't stale, it's
// static.
func (q *Queries) MarkStaleHostsUnhealthy(ctx context.Context, lastHeartbeatBefore sql.NullTime) (int64, error) {
	result, err := q.db.ExecContext(ctx, markStaleHostsUnhealthy, lastHeartbeatBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordHostHeartbeat = `-- name: RecordHostHeartbeat :exec

UPDATE hosts
SET last_heartbeat = $1,
    host_healthy = true
WHERE id = $2
`

type RecordHostHeartbeatParams struct {
	ObservedAt sql.NullTime `json:"observed_at"`
	HostID     uuid.UUID    `json:"host_id"`
}

// Observed-state writes: reports flowing IN from host agents (apiserver Ingest),
// plus the watchdog sweep that turns silence into scheduling signal. The reconcile
// loop never writes observed state and ingest/watchdog never write desired state —
// these queries are the whole boundary.
// Ingest a host agent's liveness ping. Only observed state moves: status is
// operator intent and a heartbeat must never un-cordon or un-drain a host.
func (q *Queries) RecordHostHeartbeat(ctx context.Context, arg RecordHostHeartbeatParams) error {
	_, err := q.db.ExecContext(ctx, recordHostHeartbeat, arg.ObservedAt, arg.HostID)
	return err
}

const recordReplicaObservation = `-- name: RecordReplicaObservation :execrows
UPDATE replicas
SET phase = $1,
    healthy = $2,
    restart_count = $3,
    last_exit_reason = $4,
    revision = revision + 1
WHERE id = $5
  AND phase NOT IN ('draining', 'reaped', 'failed', 'replacing')
`

type RecordReplicaObservationParams struct {
	Phase          string         `json:"phase"`
	Healthy        bool           `json:"healthy"`
	RestartCount   int32          `json:"restart_count"`
	LastExitReason sql.NullString `json:"last_exit_reason"`
	ReplicaID      uuid.UUID      `json:"replica_id"`
}

// Ingest one agent-reported replica state. Terminal and orchestrator-owned
// phases win over observations: a stale agent report must not resurrect a
// failed replica, un-drain a retiring one, or (replacing) re-legitimize a
// replica whose host was declared dead while its agent lives on across a
// partition. rows-affected = 0 just means the observation was dropped as
// stale — not an error. The healthy false→true edge stamps
// health_checks_passed_at via the table trigger.
func (q *Queries) RecordReplicaObservation(ctx context.Context, arg RecordReplicaObservationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordReplicaObservation,
		arg.Phase,
		arg.Healthy,
		arg.RestartCount,
		arg.LastExitReason,
		arg.ReplicaID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordVolumeObservedSize = `-- name: RecordVolumeObservedSize :exec
UPDATE volumes
SET observed_size_bytes = $1
WHERE id = $2
`

type RecordVolumeObservedSizeParams struct {
	ObservedBytes sql.NullInt64 `json:"observed_bytes"`
	VolumeID      uuid.UUID     `json:"volume_id"`
}

// Observed volume size (grow-only resize drift, §4b): what the agent reports
// is on disk. Unguarded — observed state has one writer per volume (its host's
// agent) and the reconcile loop only ever reads it.
func (q *Queries) RecordVolumeObservedSize(ctx context.Context, arg RecordVolumeObservedSizeParams) error {
	_, err := q.db.ExecContext(ctx, recordVolumeObservedSize, arg.ObservedBytes, arg.VolumeID)
	return err
}

const renewVolumeLease = `-- name: RenewVolumeLease :execrows
UPDATE volume_leases
SET expires_at = $1
WHERE replica_id = $2
`

type RenewVolumeLeaseParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	ReplicaID uuid.UUID `json:"replica_id"`
}

// Extend the lease this replica holds — the renewal a healthy observation
// carries, so a live stateful replica's lease never runs out. Keyed by holder:
// a lease another replica has since claimed is never touched (their upsert
// overwrote replica_id). Extending our own lease past a silent gap is safe —
// expiry only matters once a competitor claims the volume, and then this
// UPDATE matches nothing. rows-affected = 0 just means "no lease held here"
// (stateless replica, or the volume moved on) — not an error.
func (q *Queries) RenewVolumeLease(ctx context.Context, arg RenewVolumeLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewVolumeLease, arg.ExpiresAt, arg.ReplicaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
