// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sensor.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const listAgentHosts = `-- name: ListAgentHosts :many
SELECT id, region, hostname, cpu_millicores, mem_bytes, disk_bytes, labels, status, last_heartbeat, created_at FROM hosts
`

// Agent discovery: every host an agent could run on. Scheduling status is
// deliberately ignored — an agent lives on the machine regardless, and a
// notready host's agent must be able to enroll and heartbeat or a demoted
// host could never heal back to ready.
func (q *Queries) ListAgentHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.QueryContext(ctx, listAgentHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.Hostname,
			&i.CpuMillicores,
			&i.MemBytes,
			&i.DiskBytes,
			&i.Labels,
			&i.Status,
			&i.LastHeartbeat,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeadHosts = `-- name: ListDeadHosts :many
SELECT hosts.id, hosts.region, hosts.hostname, hosts.cpu_millicores, hosts.mem_bytes, hosts.disk_bytes, hosts.labels, hosts.status, hosts.last_heartbeat, hosts.created_at FROM hosts
WHERE status IN ('ready', 'notready')
  AND last_heartbeat IS NOT NULL
  AND last_heartbeat < $1
  AND EXISTS (
      SELECT 1 FROM replicas r
      WHERE r.host_id = hosts.id
        AND r.phase NOT IN ('reaped', 'failed')
        AND r.drained_at IS NULL
  )
`

// Second staleness threshold: hosts silent long enough to be declared dead,
// listed for MarkHostDown. Includes notready (the first threshold already
// demoted them) but not cordoned/draining — those are operator desired state.
// The EXISTS keeps the list level-triggered and self-quieting: once a host's
// replicas are freed it stops matching, so an already-downed host isn't
// re-marked every sweep.
func (q *Queries) ListDeadHosts(ctx context.Context, lastHeartbeatBefore sql.NullTime) ([]Host, error) {
	rows, err := q.db.QueryContext(ctx, listDeadHosts, lastHeartbeatBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.Hostname,
			&i.CpuMillicores,
			&i.MemBytes,
			&i.DiskBytes,
			&i.Labels,
			&i.Status,
			&i.LastHeartbeat,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReplicasByHost = `-- name: ListReplicasByHost :many
SELECT id, deployment_id, region, host_id, volume_id, cpu_millicores, mem_bytes, alloc_reason, desired_status, phase, healthy, restart_count, last_exit_reason, revision, created_at, updated_at, drained_at, health_checks_passed_at FROM replicas
WHERE host_id = $1 AND phase <> 'reaped'
`

// The replicas a host agent is responsible for driving (start scheduling,
// drain draining, report the rest).
func (q *Queries) ListReplicasByHost(ctx context.Context, hostID uuid.NullUUID) ([]Replica, error) {
	rows, err := q.db.QueryContext(ctx, listReplicasByHost, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Replica
	for rows.Next() {
		var i Replica
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Region,
			&i.HostID,
			&i.VolumeID,
			&i.CpuMillicores,
			&i.MemBytes,
			&i.AllocReason,
			&i.DesiredStatus,
			&i.Phase,
			&i.Healthy,
			&i.RestartCount,
			&i.LastExitReason,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DrainedAt,
			&i.HealthChecksPassedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markHostDown = `-- name: MarkHostDown :exec
WITH downed AS (
    UPDATE hosts SET status = 'notready'
    WHERE hosts.id = $1
      AND hosts.status IN ('ready', 'notready')
      AND hosts.last_heartbeat IS NOT NULL
      AND hosts.last_heartbeat < $2
    RETURNING hosts.id
)
UPDATE replicas
SET host_id = NULL,
    healthy = false,
    phase = 'replacing',
    revision = revision + 1
WHERE host_id IN (SELECT id FROM downed)
  AND phase NOT IN ('reaped', 'failed')
  AND drained_at IS NULL
`

type MarkHostDownParams struct {
	HostID              uuid.UUID    `json:"host_id"`
	LastHeartbeatBefore sql.NullTime `json:"last_heartbeat_before"`
}

// Take a dead host out of scheduling and free its replicas in one atomic
// statement: a downed host with still-bound replicas is invisible to the
// Reconciler (anyHostlessReplicas keys on host_id IS NULL), so the two writes
// must never be observable apart. Replicas drop to hostless 'replacing' — the
// placer reads it as a replacement (skips the headroom reserve), and the
// observation guard below owns it, so a partitioned-but-alive agent can't
// resurrect a freed replica. Already-draining replicas keep their host
// binding: they're retiring on the drain window regardless, and unassigning
// them would erase the drain state.
// The WHERE re-asserts staleness: a heartbeat landing between the sweep's
// ListStaleHosts and this write refreshes last_heartbeat, so the recovered
// host matches nothing and keeps its replicas — downing rides on the
// predicate, not on the sweep's possibly-stale list.
func (q *Queries) MarkHostDown(ctx context.Context, arg MarkHostDownParams) error {
	_, err := q.db.ExecContext(ctx, markHostDown, arg.HostID, arg.LastHeartbeatBefore)
	return err
}

const markStaleHostsNotReady = `-- name: MarkStaleHostsNotReady :execrows
UPDATE hosts
SET status = 'notready'
WHERE status = 'ready'
  AND last_heartbeat IS NOT NULL
  AND last_heartbeat < $1
`

// First staleness threshold: a briefly-silent host stops receiving NEW work
// (placer skips notready) but keeps its replicas — cheap and reversible, the
// next heartbeat flips it straight back to ready. One fleet-wide statement,
// no per-host loop. NULL last_heartbeat is excluded: a host that never
// enrolled an agent (seeded dev fleet) isn't stale, it's static.
func (q *Queries) MarkStaleHostsNotReady(ctx context.Context, lastHeartbeatBefore sql.NullTime) (int64, error) {
	result, err := q.db.ExecContext(ctx, markStaleHostsNotReady, lastHeartbeatBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordHostHeartbeat = `-- name: RecordHostHeartbeat :exec

UPDATE hosts
SET last_heartbeat = $1,
    status = CASE WHEN status IN ('ready', 'notready') THEN $2 ELSE status END
WHERE id = $3
`

type RecordHostHeartbeatParams struct {
	ObservedAt sql.NullTime `json:"observed_at"`
	Status     string       `json:"status"`
	HostID     uuid.UUID    `json:"host_id"`
}

// Sensor-path writes: observed state flowing IN from host agents, plus the
// staleness sweep that turns silence into scheduling signal. The reconcile
// loop never writes observed state and the sensor never writes desired state —
// these queries are the whole boundary.
// Ingest a host agent's liveness ping. Status only moves between the
// agent-owned states (ready/notready): a heartbeat must never un-cordon a host
// an operator cordoned or is draining — those are desired-state decisions, not
// observations.
func (q *Queries) RecordHostHeartbeat(ctx context.Context, arg RecordHostHeartbeatParams) error {
	_, err := q.db.ExecContext(ctx, recordHostHeartbeat, arg.ObservedAt, arg.Status, arg.HostID)
	return err
}

const recordReplicaObservation = `-- name: RecordReplicaObservation :execrows
UPDATE replicas
SET phase = $1,
    healthy = $2,
    restart_count = $3,
    last_exit_reason = $4,
    revision = revision + 1
WHERE id = $5
  AND phase NOT IN ('draining', 'reaped', 'failed', 'replacing')
`

type RecordReplicaObservationParams struct {
	Phase          string         `json:"phase"`
	Healthy        bool           `json:"healthy"`
	RestartCount   int32          `json:"restart_count"`
	LastExitReason sql.NullString `json:"last_exit_reason"`
	ReplicaID      uuid.UUID      `json:"replica_id"`
}

// Ingest one agent-reported replica state. Terminal and orchestrator-owned
// phases win over observations: a stale agent report must not resurrect a
// failed replica, un-drain a retiring one, or (replacing) re-legitimize a
// replica whose host was declared dead while its agent lives on across a
// partition. rows-affected = 0 just means the observation was dropped as
// stale — not an error. The healthy false→true edge stamps
// health_checks_passed_at via the table trigger.
func (q *Queries) RecordReplicaObservation(ctx context.Context, arg RecordReplicaObservationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recordReplicaObservation,
		arg.Phase,
		arg.Healthy,
		arg.RestartCount,
		arg.LastExitReason,
		arg.ReplicaID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordVolumeObservedSize = `-- name: RecordVolumeObservedSize :exec
UPDATE volumes
SET observed_size_bytes = $1
WHERE id = $2
`

type RecordVolumeObservedSizeParams struct {
	ObservedBytes sql.NullInt64 `json:"observed_bytes"`
	VolumeID      uuid.UUID     `json:"volume_id"`
}

// Observed volume size (grow-only resize drift, §4b).
func (q *Queries) RecordVolumeObservedSize(ctx context.Context, arg RecordVolumeObservedSizeParams) error {
	_, err := q.db.ExecContext(ctx, recordVolumeObservedSize, arg.ObservedBytes, arg.VolumeID)
	return err
}

const renewVolumeLease = `-- name: RenewVolumeLease :execrows
UPDATE volume_leases
SET expires_at = $1
WHERE replica_id = $2
`

type RenewVolumeLeaseParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	ReplicaID uuid.UUID `json:"replica_id"`
}

// Extend the lease this replica holds — the renewal a healthy observation
// carries, so a live stateful replica's lease never runs out. Keyed by holder:
// a lease another replica has since claimed is never touched (their upsert
// overwrote replica_id). Extending our own lease past a silent gap is safe —
// expiry only matters once a competitor claims the volume, and then this
// UPDATE matches nothing. rows-affected = 0 just means "no lease held here"
// (stateless replica, or the volume moved on) — not an error.
func (q *Queries) RenewVolumeLease(ctx context.Context, arg RenewVolumeLeaseParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, renewVolumeLease, arg.ExpiresAt, arg.ReplicaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
