// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshot.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listActiveReplicas = `-- name: ListActiveReplicas :many
SELECT r.id, r.deployment_id, r.region, r.host_id, r.volume_id, r.cpu_millicores, r.mem_bytes, r.alloc_reason, r.desired_status, r.phase, r.healthy, r.restart_count, r.last_exit_reason, r.revision, r.created_at, r.updated_at FROM replicas r
JOIN deployments d ON d.id = r.deployment_id
WHERE d.is_current AND r.phase <> 'reaped'
`

// Observed fleet: every replica under a current deployment, the set the diff
// compares against SnapshotDesired. Reaped replicas are terminal and excluded.
func (q *Queries) ListActiveReplicas(ctx context.Context) ([]Replica, error) {
	rows, err := q.db.QueryContext(ctx, listActiveReplicas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Replica
	for rows.Next() {
		var i Replica
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Region,
			&i.HostID,
			&i.VolumeID,
			&i.CpuMillicores,
			&i.MemBytes,
			&i.AllocReason,
			&i.DesiredStatus,
			&i.Phase,
			&i.Healthy,
			&i.RestartCount,
			&i.LastExitReason,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveVolumes = `-- name: ListActiveVolumes :many
SELECT DISTINCT v.id, v.service_id, v.name, v.mount_path, v.region, v.host_id, v.backing, v.desired_size_bytes, v.observed_size_bytes, v.status, v.revision, v.created_at FROM volumes v
JOIN environment_services es ON es.service_id = v.service_id
JOIN deployments d           ON d.environment_service_id = es.id
WHERE d.is_current
`

// Volumes for services that have a current deployment — the disks a stateful
// placement pins and leases. Keyed by (service_id, region) against the stateful
// rows of SnapshotDesired. DISTINCT collapses a service shared across multiple
// environments (the lease is re-checked inside the reconcile tx regardless).
func (q *Queries) ListActiveVolumes(ctx context.Context) ([]Volume, error) {
	rows, err := q.db.QueryContext(ctx, listActiveVolumes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Volume
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.MountPath,
			&i.Region,
			&i.HostID,
			&i.Backing,
			&i.DesiredSizeBytes,
			&i.ObservedSizeBytes,
			&i.Status,
			&i.Revision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulableHosts = `-- name: ListSchedulableHosts :many
SELECT id, region, hostname, cpu_millicores, mem_bytes, disk_bytes, labels, status, last_heartbeat, revision, created_at FROM hosts WHERE status = 'ready'
`

// Hosts eligible to receive placements this pass: 'ready' only (notready,
// draining, cordoned are skipped). All regions — the Scheduler buckets by region.
func (q *Queries) ListSchedulableHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulableHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.Hostname,
			&i.CpuMillicores,
			&i.MemBytes,
			&i.DiskBytes,
			&i.Labels,
			&i.Status,
			&i.LastHeartbeat,
			&i.Revision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotDesired = `-- name: SnapshotDesired :many

SELECT
	d.id             AS deployment_id,
	svc.id           AS service_id,
	dr.region        AS region,
	dr.replicas      AS desired_replicas,
	d.cpu_millicores AS cpu_millicores,
	d.mem_bytes      AS mem_bytes,
	svc.stateful     AS stateful
FROM deployments d
JOIN deployment_regions dr   ON dr.deployment_id = d.id
JOIN environment_services es ON es.id = d.environment_service_id
JOIN services svc            ON svc.id = es.service_id
WHERE d.is_current
`

type SnapshotDesiredRow struct {
	DeploymentID    uuid.UUID `json:"deployment_id"`
	ServiceID       uuid.UUID `json:"service_id"`
	Region          string    `json:"region"`
	DesiredReplicas int32     `json:"desired_replicas"`
	CpuMillicores   int32     `json:"cpu_millicores"`
	MemBytes        int64     `json:"mem_bytes"`
	Stateful        bool      `json:"stateful"`
}

// Reconcile-read path. The Scheduler runs these three together inside a single
// read-only REPEATABLE READ tx (storage.WithReadTx) so the desired and observed
// halves of a pass observe one frozen snapshot — desired can't scale out from
// under the replica list between queries, which would tear the placement diff.
// Desired state: one row per (current deployment, region) carrying the replica
// target plus the spec the Scheduler needs to mint a replica. Joined to services
// for the stateful flag, which selects the volume/lease placement path.
func (q *Queries) SnapshotDesired(ctx context.Context) ([]SnapshotDesiredRow, error) {
	rows, err := q.db.QueryContext(ctx, snapshotDesired)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotDesiredRow
	for rows.Next() {
		var i SnapshotDesiredRow
		if err := rows.Scan(
			&i.DeploymentID,
			&i.ServiceID,
			&i.Region,
			&i.DesiredReplicas,
			&i.CpuMillicores,
			&i.MemBytes,
			&i.Stateful,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
