// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: snapshot.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const listActiveReplicas = `-- name: ListActiveReplicas :many
SELECT r.id, r.deployment_id, r.region, r.host_id, r.volume_id, r.cpu_millicores, r.mem_bytes, r.alloc_reason, r.desired_status, r.phase, r.healthy, r.restart_count, r.last_exit_reason, r.revision, r.created_at, r.updated_at, r.drained_at, r.health_checks_passed_at, d.environment_service_id, es.service_id, d.version, d.is_current, d.drain_seconds
FROM replicas r
JOIN deployments d           ON d.id = r.deployment_id
JOIN environment_services es ON es.id = d.environment_service_id
WHERE r.phase <> 'reaped'
  AND EXISTS (
    SELECT 1 FROM deployments c
    WHERE c.environment_service_id = d.environment_service_id
      AND c.is_current
  )
`

type ListActiveReplicasRow struct {
	ID                   uuid.UUID      `json:"id"`
	DeploymentID         uuid.UUID      `json:"deployment_id"`
	Region               string         `json:"region"`
	HostID               uuid.NullUUID  `json:"host_id"`
	VolumeID             uuid.NullUUID  `json:"volume_id"`
	CpuMillicores        int32          `json:"cpu_millicores"`
	MemBytes             int64          `json:"mem_bytes"`
	AllocReason          sql.NullString `json:"alloc_reason"`
	DesiredStatus        string         `json:"desired_status"`
	Phase                string         `json:"phase"`
	Healthy              bool           `json:"healthy"`
	RestartCount         int32          `json:"restart_count"`
	LastExitReason       sql.NullString `json:"last_exit_reason"`
	Revision             int64          `json:"revision"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	DrainedAt            sql.NullTime   `json:"drained_at"`
	HealthChecksPassedAt sql.NullTime   `json:"health_checks_passed_at"`
	EnvironmentServiceID uuid.UUID      `json:"environment_service_id"`
	ServiceID            uuid.UUID      `json:"service_id"`
	Version              int32          `json:"version"`
	IsCurrent            bool           `json:"is_current"`
	DrainSeconds         int32          `json:"drain_seconds"`
}

// Observed fleet for every service that has a current deployment — INCLUDING
// replicas still running under a superseded deployment (an in-flight rollout
// from version N to N+1). The orchestrator groups by (environment_service_id,
// region) and splits on is_current: is_current replicas are the new revision to
// converge toward, the rest are the old revision to drain. Filtering on
// d.is_current here would hide the outgoing replicas and leak them as orphans
// nothing ever reaps. Reaped replicas are terminal and excluded.
func (q *Queries) ListActiveReplicas(ctx context.Context) ([]ListActiveReplicasRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveReplicas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveReplicasRow
	for rows.Next() {
		var i ListActiveReplicasRow
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Region,
			&i.HostID,
			&i.VolumeID,
			&i.CpuMillicores,
			&i.MemBytes,
			&i.AllocReason,
			&i.DesiredStatus,
			&i.Phase,
			&i.Healthy,
			&i.RestartCount,
			&i.LastExitReason,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DrainedAt,
			&i.HealthChecksPassedAt,
			&i.EnvironmentServiceID,
			&i.ServiceID,
			&i.Version,
			&i.IsCurrent,
			&i.DrainSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveVolumes = `-- name: ListActiveVolumes :many
SELECT DISTINCT v.id, v.service_id, v.name, v.mount_path, v.region, v.host_id, v.backing, v.desired_size_bytes, v.observed_size_bytes, v.status, v.revision, v.created_at FROM volumes v
JOIN environment_services es ON es.service_id = v.service_id
JOIN deployments d           ON d.environment_service_id = es.id
WHERE d.is_current
`

// Volumes for services that have a current deployment — the disks a stateful
// placement pins and leases. Keyed by (service_id, region) against the stateful
// rows of SnapshotDesired. DISTINCT collapses a service shared across multiple
// environments (the lease is re-checked inside the reconcile tx regardless).
func (q *Queries) ListActiveVolumes(ctx context.Context) ([]Volume, error) {
	rows, err := q.db.QueryContext(ctx, listActiveVolumes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Volume
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.MountPath,
			&i.Region,
			&i.HostID,
			&i.Backing,
			&i.DesiredSizeBytes,
			&i.ObservedSizeBytes,
			&i.Status,
			&i.Revision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulableHosts = `-- name: ListSchedulableHosts :many
SELECT id, region, hostname, cpu_millicores, mem_bytes, disk_bytes, labels, status, last_heartbeat, revision, created_at FROM hosts WHERE status = 'ready'
`

// Hosts eligible to receive placements this pass: 'ready' only (notready,
// draining, cordoned are skipped). All regions — the Engine buckets by region.
func (q *Queries) ListSchedulableHosts(ctx context.Context) ([]Host, error) {
	rows, err := q.db.QueryContext(ctx, listSchedulableHosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Host
	for rows.Next() {
		var i Host
		if err := rows.Scan(
			&i.ID,
			&i.Region,
			&i.Hostname,
			&i.CpuMillicores,
			&i.MemBytes,
			&i.DiskBytes,
			&i.Labels,
			&i.Status,
			&i.LastHeartbeat,
			&i.Revision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotDesired = `-- name: SnapshotDesired :many

SELECT
	d.environment_service_id AS environment_service_id,
	d.id                     AS deployment_id,
	svc.id                   AS service_id,
	dr.region                AS region,
	dr.replicas              AS desired_replicas,
	d.cpu_millicores         AS cpu_millicores,
	d.mem_bytes              AS mem_bytes,
	d.restart_max            AS restart_max,
	d.progress_deadline      AS progress_deadline,
	d.status                 AS status,
	svc.stateful             AS stateful
FROM deployments d
JOIN deployment_regions dr   ON dr.deployment_id = d.id
JOIN environment_services es ON es.id = d.environment_service_id
JOIN services svc            ON svc.id = es.service_id
WHERE d.is_current
`

type SnapshotDesiredRow struct {
	EnvironmentServiceID uuid.UUID `json:"environment_service_id"`
	DeploymentID         uuid.UUID `json:"deployment_id"`
	ServiceID            uuid.UUID `json:"service_id"`
	Region               string    `json:"region"`
	DesiredReplicas      int32     `json:"desired_replicas"`
	CpuMillicores        int32     `json:"cpu_millicores"`
	MemBytes             int64     `json:"mem_bytes"`
	RestartMax           int32     `json:"restart_max"`
	ProgressDeadline     int32     `json:"progress_deadline"`
	Status               string    `json:"status"`
	Stateful             bool      `json:"stateful"`
}

// Reconcile-read path. The Engine runs these three together inside a single
// read-only REPEATABLE READ tx (storage.WithReadTx) so the desired and observed
// halves of a pass observe one frozen snapshot — desired can't scale out from
// under the replica list between queries, which would tear the placement diff.
// Desired state: one row per (current deployment, region) carrying the replica
// target plus the spec the Reconciler needs to mint a replica. Joined to services
// for the stateful flag, which selects the volume/lease placement path.
// environment_service_id is the reconcile grouping key (a service shared across
// environments has one current deployment per env — service_id alone would
// collide them); it ties this desired row to its replicas in ListActiveReplicas.
func (q *Queries) SnapshotDesired(ctx context.Context) ([]SnapshotDesiredRow, error) {
	rows, err := q.db.QueryContext(ctx, snapshotDesired)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SnapshotDesiredRow
	for rows.Next() {
		var i SnapshotDesiredRow
		if err := rows.Scan(
			&i.EnvironmentServiceID,
			&i.DeploymentID,
			&i.ServiceID,
			&i.Region,
			&i.DesiredReplicas,
			&i.CpuMillicores,
			&i.MemBytes,
			&i.RestartMax,
			&i.ProgressDeadline,
			&i.Status,
			&i.Stateful,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
