// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: volumes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createVolume = `-- name: CreateVolume :one

INSERT INTO volumes (service_id, name, region, mount_path, desired_size_bytes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, service_id, name, mount_path, region, host_id, backing, desired_size_bytes, observed_size_bytes, status, revision, created_at
`

type CreateVolumeParams struct {
	ServiceID        uuid.UUID `json:"service_id"`
	Name             string    `json:"name"`
	Region           string    `json:"region"`
	MountPath        string    `json:"mount_path"`
	DesiredSizeBytes int64     `json:"desired_size_bytes"`
}

// Queries backing `conductor volume`. A volume belongs to a service (not a
// single environment — volumes.service_id) and is addressed by its mount path,
// the contract with the container. Size is a mutable desired property the
// reconcile loop converges to (§4b grow-only resize); there is no create-time
// --size, so add lands a default the user patches later with `volume update`.
func (q *Queries) CreateVolume(ctx context.Context, arg CreateVolumeParams) (Volume, error) {
	row := q.db.QueryRowContext(ctx, createVolume,
		arg.ServiceID,
		arg.Name,
		arg.Region,
		arg.MountPath,
		arg.DesiredSizeBytes,
	)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Name,
		&i.MountPath,
		&i.Region,
		&i.HostID,
		&i.Backing,
		&i.DesiredSizeBytes,
		&i.ObservedSizeBytes,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVolume = `-- name: DeleteVolume :one
DELETE FROM volumes
WHERE service_id = $1 AND mount_path = $2
RETURNING id, service_id, name, mount_path, region, host_id, backing, desired_size_bytes, observed_size_bytes, status, revision, created_at
`

type DeleteVolumeParams struct {
	ServiceID uuid.UUID `json:"service_id"`
	MountPath string    `json:"mount_path"`
}

func (q *Queries) DeleteVolume(ctx context.Context, arg DeleteVolumeParams) (Volume, error) {
	row := q.db.QueryRowContext(ctx, deleteVolume, arg.ServiceID, arg.MountPath)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Name,
		&i.MountPath,
		&i.Region,
		&i.HostID,
		&i.Backing,
		&i.DesiredSizeBytes,
		&i.ObservedSizeBytes,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const listVolumesByService = `-- name: ListVolumesByService :many
SELECT v.id, v.service_id, v.name, v.mount_path, v.region, v.host_id, v.backing, v.desired_size_bytes, v.observed_size_bytes, v.status, v.revision, v.created_at FROM volumes v
JOIN services s ON s.id = v.service_id
WHERE s.project_name = $1 AND s.name = $2
ORDER BY v.mount_path
`

type ListVolumesByServiceParams struct {
	ProjectName string `json:"project_name"`
	Name        string `json:"name"`
}

func (q *Queries) ListVolumesByService(ctx context.Context, arg ListVolumesByServiceParams) ([]Volume, error) {
	rows, err := q.db.QueryContext(ctx, listVolumesByService, arg.ProjectName, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Volume
	for rows.Next() {
		var i Volume
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.MountPath,
			&i.Region,
			&i.HostID,
			&i.Backing,
			&i.DesiredSizeBytes,
			&i.ObservedSizeBytes,
			&i.Status,
			&i.Revision,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVolumeSize = `-- name: UpdateVolumeSize :one
UPDATE volumes
SET desired_size_bytes = $1
WHERE service_id = $2 AND mount_path = $3
RETURNING id, service_id, name, mount_path, region, host_id, backing, desired_size_bytes, observed_size_bytes, status, revision, created_at
`

type UpdateVolumeSizeParams struct {
	DesiredSizeBytes int64     `json:"desired_size_bytes"`
	ServiceID        uuid.UUID `json:"service_id"`
	MountPath        string    `json:"mount_path"`
}

// UpdateVolumeSize patches only the desired size; the reconcile loop notices the
// drift and flips status to 'resizing' itself. RETURNING lets the caller map a
// missing (service, mount) to not-found instead of a silent no-op.
func (q *Queries) UpdateVolumeSize(ctx context.Context, arg UpdateVolumeSizeParams) (Volume, error) {
	row := q.db.QueryRowContext(ctx, updateVolumeSize, arg.DesiredSizeBytes, arg.ServiceID, arg.MountPath)
	var i Volume
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Name,
		&i.MountPath,
		&i.Region,
		&i.HostID,
		&i.Backing,
		&i.DesiredSizeBytes,
		&i.ObservedSizeBytes,
		&i.Status,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}
