// Agent <-> control-plane contract. One bidi Session stream per host: uplink
// carries what the agent OBSERVES (heartbeats, replica states), downlink
// carries what the host SHOULD look like — always the full host state, never
// a delta, so any single message is sufficient and a lost one is healed by the
// next (level-triggered; see todo.md "agent transport").

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/agentpb/agent.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentGateway_Session_FullMethodName   = "/conductor.agent.v1.AgentGateway/Session"
	AgentGateway_ListHosts_FullMethodName = "/conductor.agent.v1.AgentGateway/ListHosts"
)

// AgentGatewayClient is the client API for AgentGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentGatewayClient interface {
	// Session is the agent's whole protocol. First uplink message must be Hello;
	// after it the server pushes HostState on every relevant change plus a
	// periodic resync, and ingests heartbeats/observations through the Sensor.
	// The stream being open is NOT liveness — only heartbeats are (the sensor
	// sweep works off their server-side timestamps).
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error)
	// ListHosts exposes the schedulable fleet so the agent simulator can spawn
	// one agent per host without its own database connection.
	ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsResponse, error)
}

type agentGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentGatewayClient(cc grpc.ClientConnInterface) AgentGatewayClient {
	return &agentGatewayClient{cc}
}

func (c *agentGatewayClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, ServerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentGateway_ServiceDesc.Streams[0], AgentGateway_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, ServerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_SessionClient = grpc.BidiStreamingClient[AgentMessage, ServerMessage]

func (c *agentGatewayClient) ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHostsResponse)
	err := c.cc.Invoke(ctx, AgentGateway_ListHosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentGatewayServer is the server API for AgentGateway service.
// All implementations must embed UnimplementedAgentGatewayServer
// for forward compatibility.
type AgentGatewayServer interface {
	// Session is the agent's whole protocol. First uplink message must be Hello;
	// after it the server pushes HostState on every relevant change plus a
	// periodic resync, and ingests heartbeats/observations through the Sensor.
	// The stream being open is NOT liveness — only heartbeats are (the sensor
	// sweep works off their server-side timestamps).
	Session(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error
	// ListHosts exposes the schedulable fleet so the agent simulator can spawn
	// one agent per host without its own database connection.
	ListHosts(context.Context, *ListHostsRequest) (*ListHostsResponse, error)
	mustEmbedUnimplementedAgentGatewayServer()
}

// UnimplementedAgentGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentGatewayServer struct{}

func (UnimplementedAgentGatewayServer) Session(grpc.BidiStreamingServer[AgentMessage, ServerMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedAgentGatewayServer) ListHosts(context.Context, *ListHostsRequest) (*ListHostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListHosts not implemented")
}
func (UnimplementedAgentGatewayServer) mustEmbedUnimplementedAgentGatewayServer() {}
func (UnimplementedAgentGatewayServer) testEmbeddedByValue()                      {}

// UnsafeAgentGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentGatewayServer will
// result in compilation errors.
type UnsafeAgentGatewayServer interface {
	mustEmbedUnimplementedAgentGatewayServer()
}

func RegisterAgentGatewayServer(s grpc.ServiceRegistrar, srv AgentGatewayServer) {
	// If the following call pancis, it indicates UnimplementedAgentGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentGateway_ServiceDesc, srv)
}

func _AgentGateway_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentGatewayServer).Session(&grpc.GenericServerStream[AgentMessage, ServerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_SessionServer = grpc.BidiStreamingServer[AgentMessage, ServerMessage]

func _AgentGateway_ListHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentGatewayServer).ListHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentGateway_ListHosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentGatewayServer).ListHosts(ctx, req.(*ListHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentGateway_ServiceDesc is the grpc.ServiceDesc for AgentGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "conductor.agent.v1.AgentGateway",
	HandlerType: (*AgentGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListHosts",
			Handler:    _AgentGateway_ListHosts_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _AgentGateway_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/agentpb/agent.proto",
}
