// Agent <-> control-plane contract. One bidi Session stream per host: uplink
// carries what the agent OBSERVES (heartbeats, replica states, disk sizes),
// downlink carries what the host SHOULD look like — always the full host
// state (replicas and volumes), never a delta, so any single message is sufficient and a lost one is healed by the
// next (level-triggered; see todo.md "agent transport").

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Observation
	//	*AgentMessage_VolumeObservation
	Msg           isAgentMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetMsg() isAgentMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetObservation() *ReplicaObservation {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Observation); ok {
			return x.Observation
		}
	}
	return nil
}

func (x *AgentMessage) GetVolumeObservation() *VolumeObservation {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_VolumeObservation); ok {
			return x.VolumeObservation
		}
	}
	return nil
}

type isAgentMessage_Msg interface {
	isAgentMessage_Msg()
}

type AgentMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Observation struct {
	Observation *ReplicaObservation `protobuf:"bytes,3,opt,name=observation,proto3,oneof"`
}

type AgentMessage_VolumeObservation struct {
	VolumeObservation *VolumeObservation `protobuf:"bytes,4,opt,name=volume_observation,json=volumeObservation,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Msg() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Msg() {}

func (*AgentMessage_Observation) isAgentMessage_Msg() {}

func (*AgentMessage_VolumeObservation) isAgentMessage_Msg() {}

// Hello binds the stream to a host. Exactly one, first.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

// Heartbeat is the liveness ping; the server stamps its own observation time
// (an agent's skewed clock must not keep a dead host alive). It carries no
// payload: the beat itself is the host's health, and scheduling status is
// operator intent the agent has no say in.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

// ReplicaObservation mirrors storage.ReplicaObservation.
type ReplicaObservation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId      string                 `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Phase          string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Healthy        bool                   `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	RestartCount   int32                  `protobuf:"varint,4,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	LastExitReason string                 `protobuf:"bytes,5,opt,name=last_exit_reason,json=lastExitReason,proto3" json:"last_exit_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplicaObservation) Reset() {
	*x = ReplicaObservation{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaObservation) ProtoMessage() {}

func (x *ReplicaObservation) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaObservation.ProtoReflect.Descriptor instead.
func (*ReplicaObservation) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ReplicaObservation) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *ReplicaObservation) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ReplicaObservation) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ReplicaObservation) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *ReplicaObservation) GetLastExitReason() string {
	if x != nil {
		return x.LastExitReason
	}
	return ""
}

// VolumeObservation is what the agent has on disk for one volume. The control
// plane compares it against the desired size to notice resize drift and to
// settle a resize once the disk has caught up.
type VolumeObservation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VolumeId          string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	ObservedSizeBytes int64                  `protobuf:"varint,2,opt,name=observed_size_bytes,json=observedSizeBytes,proto3" json:"observed_size_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VolumeObservation) Reset() {
	*x = VolumeObservation{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeObservation) ProtoMessage() {}

func (x *VolumeObservation) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeObservation.ProtoReflect.Descriptor instead.
func (*VolumeObservation) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *VolumeObservation) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *VolumeObservation) GetObservedSizeBytes() int64 {
	if x != nil {
		return x.ObservedSizeBytes
	}
	return 0
}

type ServerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *HostState             `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ServerMessage) GetState() *HostState {
	if x != nil {
		return x.State
	}
	return nil
}

// HostState is the FULL set of replicas and volumes bound to the host. A
// replica present in phase scheduling is the signal to start it; draining to
// stop it; absent means gone (reaped or moved) — the agent removes anything it
// runs that the state no longer lists. A volume present is a disk to have at
// size_bytes: create it on first sight, grow it when the size exceeds what's
// on disk (never shrink), delete it when absent.
type HostState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replicas      []*Replica             `protobuf:"bytes,1,rep,name=replicas,proto3" json:"replicas,omitempty"`
	Volumes       []*Volume              `protobuf:"bytes,2,rep,name=volumes,proto3" json:"volumes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostState) Reset() {
	*x = HostState{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostState) ProtoMessage() {}

func (x *HostState) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostState.ProtoReflect.Descriptor instead.
func (*HostState) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *HostState) GetReplicas() []*Replica {
	if x != nil {
		return x.Replicas
	}
	return nil
}

func (x *HostState) GetVolumes() []*Volume {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type Replica struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Replica) Reset() {
	*x = Replica{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Replica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replica) ProtoMessage() {}

func (x *Replica) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replica.ProtoReflect.Descriptor instead.
func (*Replica) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *Replica) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Replica) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

// Volume is the size the agent should converge the disk to — NOT the raw
// desired size. The control plane hands out the new desired size only once
// the engine has approved the grow against host capacity; until then the
// agent keeps seeing what it already has.
type Volume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MountPath     string                 `protobuf:"bytes,2,opt,name=mount_path,json=mountPath,proto3" json:"mount_path,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Volume) Reset() {
	*x = Volume{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Volume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Volume) ProtoMessage() {}

func (x *Volume) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Volume.ProtoReflect.Descriptor instead.
func (*Volume) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *Volume) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Volume) GetMountPath() string {
	if x != nil {
		return x.MountPath
	}
	return ""
}

func (x *Volume) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type ListHostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostsRequest) Reset() {
	*x = ListHostsRequest{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsRequest) ProtoMessage() {}

func (x *ListHostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsRequest.ProtoReflect.Descriptor instead.
func (*ListHostsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

type ListHostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*Host                `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostsResponse) Reset() {
	*x = ListHostsResponse{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsResponse) ProtoMessage() {}

func (x *ListHostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsResponse.ProtoReflect.Descriptor instead.
func (*ListHostsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ListHostsResponse) GetHosts() []*Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type Host struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *Host) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Host) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Host) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x12conductor.agent.v1\"\xab\x02\n" +
	"\fAgentMessage\x121\n" +
	"\x05hello\x18\x01 \x01(\v2\x19.conductor.agent.v1.HelloH\x00R\x05hello\x12=\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1d.conductor.agent.v1.HeartbeatH\x00R\theartbeat\x12J\n" +
	"\vobservation\x18\x03 \x01(\v2&.conductor.agent.v1.ReplicaObservationH\x00R\vobservation\x12V\n" +
	"\x12volume_observation\x18\x04 \x01(\v2%.conductor.agent.v1.VolumeObservationH\x00R\x11volumeObservationB\x05\n" +
	"\x03msg\" \n" +
	"\x05Hello\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\"\x11\n" +
	"\tHeartbeatJ\x04\b\x01\x10\x02\"\xb2\x01\n" +
	"\x12ReplicaObservation\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\x12#\n" +
	"\rrestart_count\x18\x04 \x01(\x05R\frestartCount\x12(\n" +
	"\x10last_exit_reason\x18\x05 \x01(\tR\x0elastExitReason\"`\n" +
	"\x11VolumeObservation\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12.\n" +
	"\x13observed_size_bytes\x18\x02 \x01(\x03R\x11observedSizeBytes\"D\n" +
	"\rServerMessage\x123\n" +
	"\x05state\x18\x01 \x01(\v2\x1d.conductor.agent.v1.HostStateR\x05state\"z\n" +
	"\tHostState\x127\n" +
	"\breplicas\x18\x01 \x03(\v2\x1b.conductor.agent.v1.ReplicaR\breplicas\x124\n" +
	"\avolumes\x18\x02 \x03(\v2\x1a.conductor.agent.v1.VolumeR\avolumes\"/\n" +
	"\aReplica\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\"V\n" +
	"\x06Volume\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"mount_path\x18\x02 \x01(\tR\tmountPath\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x03R\tsizeBytes\"\x12\n" +
	"\x10ListHostsRequest\"C\n" +
	"\x11ListHostsResponse\x12.\n" +
	"\x05hosts\x18\x01 \x03(\v2\x18.conductor.agent.v1.HostR\x05hosts\"J\n" +
	"\x04Host\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname2\xb8\x01\n" +
	"\bAgentAPI\x12R\n" +
	"\aSession\x12 .conductor.agent.v1.AgentMessage\x1a!.conductor.agent.v1.ServerMessage(\x010\x01\x12X\n" +
	"\tListHosts\x12$.conductor.agent.v1.ListHostsRequest\x1a%.conductor.agent.v1.ListHostsResponseB\x19Z\x17conductor/proto/agentpbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_agent_proto_goTypes = []any{
	(*AgentMessage)(nil),       // 0: conductor.agent.v1.AgentMessage
	(*Hello)(nil),              // 1: conductor.agent.v1.Hello
	(*Heartbeat)(nil),          // 2: conductor.agent.v1.Heartbeat
	(*ReplicaObservation)(nil), // 3: conductor.agent.v1.ReplicaObservation
	(*VolumeObservation)(nil),  // 4: conductor.agent.v1.VolumeObservation
	(*ServerMessage)(nil),      // 5: conductor.agent.v1.ServerMessage
	(*HostState)(nil),          // 6: conductor.agent.v1.HostState
	(*Replica)(nil),            // 7: conductor.agent.v1.Replica
	(*Volume)(nil),             // 8: conductor.agent.v1.Volume
	(*ListHostsRequest)(nil),   // 9: conductor.agent.v1.ListHostsRequest
	(*ListHostsResponse)(nil),  // 10: conductor.agent.v1.ListHostsResponse
	(*Host)(nil),               // 11: conductor.agent.v1.Host
}
var file_agent_proto_depIdxs = []int32{
	1,  // 0: conductor.agent.v1.AgentMessage.hello:type_name -> conductor.agent.v1.Hello
	2,  // 1: conductor.agent.v1.AgentMessage.heartbeat:type_name -> conductor.agent.v1.Heartbeat
	3,  // 2: conductor.agent.v1.AgentMessage.observation:type_name -> conductor.agent.v1.ReplicaObservation
	4,  // 3: conductor.agent.v1.AgentMessage.volume_observation:type_name -> conductor.agent.v1.VolumeObservation
	6,  // 4: conductor.agent.v1.ServerMessage.state:type_name -> conductor.agent.v1.HostState
	7,  // 5: conductor.agent.v1.HostState.replicas:type_name -> conductor.agent.v1.Replica
	8,  // 6: conductor.agent.v1.HostState.volumes:type_name -> conductor.agent.v1.Volume
	11, // 7: conductor.agent.v1.ListHostsResponse.hosts:type_name -> conductor.agent.v1.Host
	0,  // 8: conductor.agent.v1.AgentAPI.Session:input_type -> conductor.agent.v1.AgentMessage
	9,  // 9: conductor.agent.v1.AgentAPI.ListHosts:input_type -> conductor.agent.v1.ListHostsRequest
	5,  // 10: conductor.agent.v1.AgentAPI.Session:output_type -> conductor.agent.v1.ServerMessage
	10, // 11: conductor.agent.v1.AgentAPI.ListHosts:output_type -> conductor.agent.v1.ListHostsResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Observation)(nil),
		(*AgentMessage_VolumeObservation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
