// Agent <-> control-plane contract. One bidi Session stream per host: uplink
// carries what the agent OBSERVES (heartbeats, replica states), downlink
// carries what the host SHOULD look like — always the full host state, never
// a delta, so any single message is sufficient and a lost one is healed by the
// next (level-triggered; see todo.md "agent transport").

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/agentpb/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Observation
	Msg           isAgentMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_agentpb_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentpb_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_agentpb_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetMsg() isAgentMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetObservation() *ReplicaObservation {
	if x != nil {
		if x, ok := x.Msg.(*AgentMessage_Observation); ok {
			return x.Observation
		}
	}
	return nil
}

type isAgentMessage_Msg interface {
	isAgentMessage_Msg()
}

type AgentMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Observation struct {
	Observation *ReplicaObservation `protobuf:"bytes,3,opt,name=observation,proto3,oneof"`
}

func (*AgentMessage_Hello) isAgentMessage_Msg() {}

func (*AgentMessage_Heartbeat) isAgentMessage_Msg() {}

func (*AgentMessage_Observation) isAgentMessage_Msg() {}

// Hello binds the stream to a host. Exactly one, first.
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_proto_agentpb_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentpb_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_proto_agentpb_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

// Heartbeat is the liveness ping; the server stamps its own observation time
// (an agent's skewed clock must not keep a dead host alive).
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "ready" | "notready"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_agentpb_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentpb_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_agentpb_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ReplicaObservation mirrors storage.ReplicaObservation.
type ReplicaObservation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReplicaId      string                 `protobuf:"bytes,1,opt,name=replica_id,json=replicaId,proto3" json:"replica_id,omitempty"`
	Phase          string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Healthy        bool                   `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	RestartCount   int32                  `protobuf:"varint,4,opt,name=restart_count,json=restartCount,proto3" json:"restart_count,omitempty"`
	LastExitReason string                 `protobuf:"bytes,5,opt,name=last_exit_reason,json=lastExitReason,proto3" json:"last_exit_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplicaObservation) Reset() {
	*x = ReplicaObservation{}
	mi := &file_proto_agentpb_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicaObservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicaObservation) ProtoMessage() {}

func (x *ReplicaObservation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentpb_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicaObservation.ProtoReflect.Descriptor instead.
func (*ReplicaObservation) Descriptor() ([]byte, []int) {
	return file_proto_agentpb_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ReplicaObservation) GetReplicaId() string {
	if x != nil {
		return x.ReplicaId
	}
	return ""
}

func (x *ReplicaObservation) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *ReplicaObservation) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ReplicaObservation) GetRestartCount() int32 {
	if x != nil {
		return x.RestartCount
	}
	return 0
}

func (x *ReplicaObservation) GetLastExitReason() string {
	if x != nil {
		return x.LastExitReason
	}
	return ""
}

type ServerMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         *HostState             `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_proto_agentpb_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentpb_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_agentpb_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ServerMessage) GetState() *HostState {
	if x != nil {
		return x.State
	}
	return nil
}

// HostState is the FULL set of replicas bound to the host. A replica present
// in phase scheduling is the signal to start it; draining to stop it; absent
// means gone (reaped or moved) — the agent removes anything it runs that the
// state no longer lists.
type HostState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Replicas      []*Replica             `protobuf:"bytes,1,rep,name=replicas,proto3" json:"replicas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostState) Reset() {
	*x = HostState{}
	mi := &file_proto_agentpb_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostState) ProtoMessage() {}

func (x *HostState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentpb_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostState.ProtoReflect.Descriptor instead.
func (*HostState) Descriptor() ([]byte, []int) {
	return file_proto_agentpb_agent_proto_rawDescGZIP(), []int{5}
}

func (x *HostState) GetReplicas() []*Replica {
	if x != nil {
		return x.Replicas
	}
	return nil
}

type Replica struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Replica) Reset() {
	*x = Replica{}
	mi := &file_proto_agentpb_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Replica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replica) ProtoMessage() {}

func (x *Replica) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentpb_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replica.ProtoReflect.Descriptor instead.
func (*Replica) Descriptor() ([]byte, []int) {
	return file_proto_agentpb_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Replica) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Replica) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

type ListHostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostsRequest) Reset() {
	*x = ListHostsRequest{}
	mi := &file_proto_agentpb_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsRequest) ProtoMessage() {}

func (x *ListHostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentpb_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsRequest.ProtoReflect.Descriptor instead.
func (*ListHostsRequest) Descriptor() ([]byte, []int) {
	return file_proto_agentpb_agent_proto_rawDescGZIP(), []int{7}
}

type ListHostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*Host                `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostsResponse) Reset() {
	*x = ListHostsResponse{}
	mi := &file_proto_agentpb_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsResponse) ProtoMessage() {}

func (x *ListHostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentpb_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsResponse.ProtoReflect.Descriptor instead.
func (*ListHostsResponse) Descriptor() ([]byte, []int) {
	return file_proto_agentpb_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ListHostsResponse) GetHosts() []*Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type Host struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_proto_agentpb_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agentpb_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_proto_agentpb_agent_proto_rawDescGZIP(), []int{9}
}

func (x *Host) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Host) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Host) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

var File_proto_agentpb_agent_proto protoreflect.FileDescriptor

const file_proto_agentpb_agent_proto_rawDesc = "" +
	"\n" +
	"\x19proto/agentpb/agent.proto\x12\x12conductor.agent.v1\"\xd3\x01\n" +
	"\fAgentMessage\x121\n" +
	"\x05hello\x18\x01 \x01(\v2\x19.conductor.agent.v1.HelloH\x00R\x05hello\x12=\n" +
	"\theartbeat\x18\x02 \x01(\v2\x1d.conductor.agent.v1.HeartbeatH\x00R\theartbeat\x12J\n" +
	"\vobservation\x18\x03 \x01(\v2&.conductor.agent.v1.ReplicaObservationH\x00R\vobservationB\x05\n" +
	"\x03msg\" \n" +
	"\x05Hello\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\"#\n" +
	"\tHeartbeat\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xb2\x01\n" +
	"\x12ReplicaObservation\x12\x1d\n" +
	"\n" +
	"replica_id\x18\x01 \x01(\tR\treplicaId\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\x12#\n" +
	"\rrestart_count\x18\x04 \x01(\x05R\frestartCount\x12(\n" +
	"\x10last_exit_reason\x18\x05 \x01(\tR\x0elastExitReason\"D\n" +
	"\rServerMessage\x123\n" +
	"\x05state\x18\x01 \x01(\v2\x1d.conductor.agent.v1.HostStateR\x05state\"D\n" +
	"\tHostState\x127\n" +
	"\breplicas\x18\x01 \x03(\v2\x1b.conductor.agent.v1.ReplicaR\breplicas\"/\n" +
	"\aReplica\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\"\x12\n" +
	"\x10ListHostsRequest\"C\n" +
	"\x11ListHostsResponse\x12.\n" +
	"\x05hosts\x18\x01 \x03(\v2\x18.conductor.agent.v1.HostR\x05hosts\"J\n" +
	"\x04Host\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname2\xbc\x01\n" +
	"\fAgentGateway\x12R\n" +
	"\aSession\x12 .conductor.agent.v1.AgentMessage\x1a!.conductor.agent.v1.ServerMessage(\x010\x01\x12X\n" +
	"\tListHosts\x12$.conductor.agent.v1.ListHostsRequest\x1a%.conductor.agent.v1.ListHostsResponseB\x19Z\x17conductor/proto/agentpbb\x06proto3"

var (
	file_proto_agentpb_agent_proto_rawDescOnce sync.Once
	file_proto_agentpb_agent_proto_rawDescData []byte
)

func file_proto_agentpb_agent_proto_rawDescGZIP() []byte {
	file_proto_agentpb_agent_proto_rawDescOnce.Do(func() {
		file_proto_agentpb_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agentpb_agent_proto_rawDesc), len(file_proto_agentpb_agent_proto_rawDesc)))
	})
	return file_proto_agentpb_agent_proto_rawDescData
}

var file_proto_agentpb_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_agentpb_agent_proto_goTypes = []any{
	(*AgentMessage)(nil),       // 0: conductor.agent.v1.AgentMessage
	(*Hello)(nil),              // 1: conductor.agent.v1.Hello
	(*Heartbeat)(nil),          // 2: conductor.agent.v1.Heartbeat
	(*ReplicaObservation)(nil), // 3: conductor.agent.v1.ReplicaObservation
	(*ServerMessage)(nil),      // 4: conductor.agent.v1.ServerMessage
	(*HostState)(nil),          // 5: conductor.agent.v1.HostState
	(*Replica)(nil),            // 6: conductor.agent.v1.Replica
	(*ListHostsRequest)(nil),   // 7: conductor.agent.v1.ListHostsRequest
	(*ListHostsResponse)(nil),  // 8: conductor.agent.v1.ListHostsResponse
	(*Host)(nil),               // 9: conductor.agent.v1.Host
}
var file_proto_agentpb_agent_proto_depIdxs = []int32{
	1, // 0: conductor.agent.v1.AgentMessage.hello:type_name -> conductor.agent.v1.Hello
	2, // 1: conductor.agent.v1.AgentMessage.heartbeat:type_name -> conductor.agent.v1.Heartbeat
	3, // 2: conductor.agent.v1.AgentMessage.observation:type_name -> conductor.agent.v1.ReplicaObservation
	5, // 3: conductor.agent.v1.ServerMessage.state:type_name -> conductor.agent.v1.HostState
	6, // 4: conductor.agent.v1.HostState.replicas:type_name -> conductor.agent.v1.Replica
	9, // 5: conductor.agent.v1.ListHostsResponse.hosts:type_name -> conductor.agent.v1.Host
	0, // 6: conductor.agent.v1.AgentGateway.Session:input_type -> conductor.agent.v1.AgentMessage
	7, // 7: conductor.agent.v1.AgentGateway.ListHosts:input_type -> conductor.agent.v1.ListHostsRequest
	4, // 8: conductor.agent.v1.AgentGateway.Session:output_type -> conductor.agent.v1.ServerMessage
	8, // 9: conductor.agent.v1.AgentGateway.ListHosts:output_type -> conductor.agent.v1.ListHostsResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_agentpb_agent_proto_init() }
func file_proto_agentpb_agent_proto_init() {
	if File_proto_agentpb_agent_proto != nil {
		return
	}
	file_proto_agentpb_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Observation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agentpb_agent_proto_rawDesc), len(file_proto_agentpb_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agentpb_agent_proto_goTypes,
		DependencyIndexes: file_proto_agentpb_agent_proto_depIdxs,
		MessageInfos:      file_proto_agentpb_agent_proto_msgTypes,
	}.Build()
	File_proto_agentpb_agent_proto = out.File
	file_proto_agentpb_agent_proto_goTypes = nil
	file_proto_agentpb_agent_proto_depIdxs = nil
}
